"""Digital Operations V1 — shared vocabulary (no provider I/O, no model)."""

from __future__ import annotations

from enum import StrEnum


class Verb(StrEnum):
    SEARCH = "SEARCH"
    READ = "READ"
    LIST = "LIST"
    CREATE = "CREATE"
    UPDATE = "UPDATE"
    DELETE = "DELETE"
    SEND = "SEND"
    REPLY = "REPLY"
    DOWNLOAD = "DOWNLOAD"
    UPLOAD = "UPLOAD"
    ATTACH = "ATTACH"
    ARCHIVE = "ARCHIVE"
    LABEL = "LABEL"
    MOVE = "MOVE"
    RESOLVE = "RESOLVE"
    WATCH = "WATCH"
    SUBSCRIBE = "SUBSCRIBE"
    PREPARE = "PREPARE"
    EXECUTE = "EXECUTE"
    VERIFY = "VERIFY"


class Availability(StrEnum):
    NATIVE = "NATIVE"
    OPERATED = "OPERATED"
    PREPARED = "PREPARED"
    OS_MEDIATED = "OS_MEDIATED"
    UNAVAILABLE = "UNAVAILABLE"
    CONNECTION_REQUIRED = "CONNECTION_REQUIRED"


class OpStatus(StrEnum):
    COMPLETED_VERIFIED = "COMPLETED_VERIFIED"
    PREPARED = "PREPARED"
    WAITING_FOR_APPROVAL = "WAITING_FOR_APPROVAL"
    WAITING_FOR_PERSON = "WAITING_FOR_PERSON"
    WAITING_FOR_SERVICE = "WAITING_FOR_SERVICE"
    SERVICE_AUTH_REQUIRED = "SERVICE_AUTH_REQUIRED"
    SERVICE_OFFLINE = "SERVICE_OFFLINE"
    PARTIAL = "PARTIAL"
    BLOCKED = "BLOCKED"
    FAILED = "FAILED"
    UNKNOWN = "UNKNOWN"
    CLARIFY = "CLARIFY"


class AutonomyLevel(StrEnum):
    READ = "READ"
    PREPARE_ONLY = "PREPARE_ONLY"
    SEND_WITH_CONFIRMATION = "SEND_WITH_CONFIRMATION"
    SAFE_DELEGATED = "SAFE_DELEGATED"
    GOAL_SCOPED_DELEGATED = "GOAL_SCOPED_DELEGATED"


class Channel(StrEnum):
    EMAIL = "EMAIL"
    WHATSAPP = "WHATSAPP"
    MESSAGES = "MESSAGES"
    CALENDAR = "CALENDAR"
    BROWSER = "BROWSER"
    FILE = "FILE"
    MEMORY = "MEMORY"


class ContentOrigin(StrEnum):
    OWNER_REQUEST = "OWNER_REQUEST"
    SYSTEM_POLICY = "SYSTEM_POLICY"
    TRUSTED_CORE = "TRUSTED_CORE"
    EXTERNAL_CONTENT = "EXTERNAL_CONTENT"
    TOOL_EVIDENCE = "TOOL_EVIDENCE"


class ContentAuthority(StrEnum):
    OWNER_INSTRUCTION = "OWNER_INSTRUCTION"
    DATA = "DATA"


class WaitingDirection(StrEnum):
    ON_PERSON = "ON_PERSON"
    ON_OWNER = "ON_OWNER"
    ON_DOCUMENT = "ON_DOCUMENT"
    ON_DECISION = "ON_DECISION"
    ON_REPLY = "ON_REPLY"
    ON_SERVICE = "ON_SERVICE"


class InboxClass(StrEnum):
    NOISE = "NOISE"
    INFORMATIONAL = "INFORMATIONAL"
    IMPORTANT_INFORMATION = "IMPORTANT_INFORMATION"
    REQUIRES_REPLY = "REQUIRES_REPLY"
    REQUEST = "REQUEST"
    COMMITMENT_TO_ME = "COMMITMENT_TO_ME"
    COMMITMENT_BY_ME = "COMMITMENT_BY_ME"
    DECISION = "DECISION"
    DEADLINE = "DEADLINE"
    DOCUMENT = "DOCUMENT"
    MEETING = "MEETING"
    WAITING_RESOLVED = "WAITING_RESOLVED"
    SECURITY_SENSITIVE = "SECURITY_SENSITIVE"


# Mass-action hard cap. Hallucinated broad queries must not touch thousands.
MASS_ACTION_MAX = 25
OUTBOUND_RATE_PER_HOUR = 30
GMAIL_PAGE_MAX = 50
WHATSAPP_READ_BOUND = 80
