"""Train the custom "EVIE" openWakeWord head and export ONNX.

This wraps openWakeWord's official PyTorch training utility
(``openwakeword/train.py``, the same path as ``automatic_model_training.ipynb``):
a small head is trained on the frozen shared feature extractor and the result
is exported as ``.onnx``.

The upstream ``examples/custom_model.yml`` is **not** shipped in the installed
package, so the config template lives here (kept in sync with the upstream
schema). Two data paths are supported:

* ``--real-clips`` (recommended when the owner has recorded wake clips): the
  owner's real "EVIE" takes are converted to openwakeword features
  (``.npy``) with the package's bundled ONNX mel/embedding models, and the
  torch trainer runs on those features — no Piper TTS, RIRs, or background
  datasets needed.
* default: generate the config for the upstream synthetic-TTS flow.

Requires the training extras (``make ml-install`` plus ``torch``,
``torchinfo``, ``torchmetrics``, ``scipy``, ``tqdm``, ``pyyaml``). The export
lands at ``~/.ev/models/wake-openwakeword.onnx``, which the ears process and
the API already look for.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path
from typing import Any

#: Upstream custom_model.yml template (openwakeword/examples/custom_model.yml).
#: ``train.py`` requires these keys; values are filled from CLI flags.
CONFIG_TEMPLATE = """# Generated by clients/ears/train/train_head.py
model_name: "{model_name}"
target_phrase:
  - "{target_phrase}"
custom_negative_phrases: []
n_samples: {n_samples}
n_samples_val: {n_samples_val}
tts_batch_size: 50
augmentation_batch_size: 16
piper_sample_generator_path: "{piper_path}"
output_dir: "{output_dir}"
rir_paths:
  - "{rir_path}"
background_paths:
  - "{background_path}"
background_paths_duplication_rate:
  - 1
false_positive_validation_data_path: "{fp_validation_path}"
augmentation_rounds: 1
feature_data_files:
{feature_data_files}
batch_n_per_class:
{feature_weights}
model_type: "dnn"
layer_size: 32
steps: {steps}
max_negative_weight: 1500
target_false_positives_per_hour: 0.2
"""


def _require_torch() -> None:
    """Fail with the exact install command when the torch training stack is absent."""

    missing = [name for name in ("torch", "torchinfo", "torchmetrics") if _not_importable(name)]
    if not missing:
        return
    raise SystemExit(
        "Missing training dependencies: "
        + ", ".join(missing)
        + ".\n"
        "Install them, then re-run:\n"
        "  cd backend && uv pip install torch torchinfo torchmetrics scipy tqdm pyyaml\n"
        "or add an `ml-train` extra and use `make wake-train`."
    )


def _not_importable(name: str) -> bool:
    try:
        __import__(name)
    except ImportError:
        return True
    return False


def _pkg_example() -> Path | None:
    """Locate the upstream example config if the installed package ships it."""

    try:
        import openwakeword
    except ImportError as exc:
        raise RuntimeError(
            "openwakeword is not installed (Agent 2 dependency request). "
            "It is required to train and export the custom EVIE head."
        ) from exc
    candidate = Path(openwakeword.__file__).resolve().parent.parent / "examples" / "custom_model.yml"
    return candidate if candidate.is_file() else None


def _write_config(
    out: Path,
    *,
    model_name: str,
    target_phrase: str,
    output_dir: Path,
    feature_data_files: dict[str, str],
    feature_weights: dict[str, int],
    steps: int = 50000,
    n_samples: int = 10000,
    n_samples_val: int = 2000,
) -> Path:
    """Render the config from the embedded upstream template."""

    if not feature_data_files:
        raise SystemExit(
            "No feature files configured. Provide --real-clips (with positive and "
            "negative clip directories) or edit the generated config."
        )
    files_block = "\n".join(
        f'  "{name}": "{path}"' for name, path in feature_data_files.items()
    )
    weights_block = "\n".join(
        f'  "{name}": {weight}' for name, weight in feature_weights.items()
    )
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        CONFIG_TEMPLATE.format(
            model_name=model_name,
            target_phrase=target_phrase,
            n_samples=n_samples,
            n_samples_val=n_samples_val,
            piper_path="./piper-sample-generator",
            output_dir=str(output_dir),
            rir_path="./mit_rirs",
            background_path="./background_clips",
            fp_validation_path="./validation_set_features.npy",
            feature_data_files=files_block,
            feature_weights=weights_block,
            steps=steps,
        ),
        encoding="utf-8",
    )
    return out


def _features_from_clips(
    clips: list[Path],
    out_path: Path,
    *,
    label: str,
    positive: bool,
) -> Path:
    """Compute openwakeword features (.npy) from real clips.

    Uses the package's bundled ONNX melspectrogram + speech-embedding models so
    real wake clips train the head without synthetic TTS generation. The array
    is the concatenation of per-clip embedding windows.
    """

    import numpy as np
    from openwakeword.utils import AudioFeatures

    from clients.ears.train.common import load_wav_pcm16

    if not clips:
        raise SystemExit(f"{label}: no clips found")
    features = AudioFeatures(inference_framework="onnx", device="cpu")
    rows: list[np.ndarray] = []
    for index, clip in enumerate(sorted(clips)):
        samples, rate = load_wav_pcm16(clip, target_rate=16000)
        if positive and len(samples) < 16000:
            samples.extend([0] * (16000 - len(samples)))
        arr = np.asarray(samples, dtype=np.int16).reshape(-1)
        rows.append(_clip_features(features, arr))
        if (index + 1) % 25 == 0:
            print(f"  features: {index + 1}/{len(clips)} ({label})")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    np.save(out_path, np.concatenate(rows, axis=0))
    print(f"{label}: {len(rows)} clips -> {out_path}")
    return out_path


def _clip_features(features, arr: Any) -> Any:
    """Return a (n_frames, dim) feature window for one clip."""

    import numpy as np

    window_size = 76
    step_size = 8
    window = features.melspec_model_predict(
        arr.astype(np.float32).reshape(1, -1) / 32768.0
    )[0]
    # Expected shape (1, 96, frames) -> (frames, 96); then slide the embedding
    # model over 76-step windows exactly like the runtime feature extractor.
    spec = np.transpose(window.squeeze(0))
    windows = []
    for i in range(0, max(1, spec.shape[0] - window_size + 1), step_size):
        chunk = spec[i : i + window_size]
        if chunk.shape[0] == window_size:
            windows.append(chunk)
    if not windows:
        windows.append(spec[:window_size] if spec.shape[0] >= window_size else spec)
    embed = np.asarray(windows, dtype=np.float32)
    if embed.ndim == 2:
        embed = embed.reshape(1, *embed.shape)
    preds = features.embedding_model_predict(embed)
    return np.asarray(preds).reshape(-1, preds.shape[-1])


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model-name", default="wake-openwakeword")
    parser.add_argument("--target-phrase", default="EVIE")
    parser.add_argument("--positive-dir", required=True, help="owner 'EVIE' clips (wav)")
    parser.add_argument("--negative-dir", default=None, help="non-wake speech/ambient clips")
    parser.add_argument("--output-dir", default="~/.ev/models")
    parser.add_argument(
        "--real-clips",
        action="store_true",
        help="train on real recorded clips (no Piper TTS generation)",
    )
    parser.add_argument("--steps", type=int, default=50000)
    parser.add_argument(
        "--no-train",
        action="store_true",
        help="only generate the config/features and print the command",
    )
    args = parser.parse_args(argv)

    positive_dir = Path(args.positive_dir).expanduser()
    output_dir = Path(args.output_dir).expanduser()
    output_dir.mkdir(parents=True, exist_ok=True)
    target = (args.target_phrase or "EVIE").upper()

    _require_torch()
    train_py = _find_train_py()

    if args.real_clips:
        feature_files: dict[str, str] = {}
        feature_weights: dict[str, int] = {}
        pos_features = output_dir / "evie_features_positive.npy"
        _features_from_clips(
            _iter_clips(positive_dir), pos_features, label="positive", positive=True
        )
        feature_files["positive"] = str(pos_features)
        feature_weights["positive"] = 256
        if args.negative_dir:
            neg_features = output_dir / "evie_features_negative.npy"
            _features_from_clips(
                _iter_clips(Path(args.negative_dir).expanduser()),
                neg_features,
                label="negative",
                positive=False,
            )
            feature_files["adversarial_negative"] = str(neg_features)
            feature_weights["adversarial_negative"] = 128
    else:
        feature_files = {
            "ACAV100M_sample": str(output_dir / "openwakeword_features_ACAV100M_2000_hrs_16bit.npy")
        }
        feature_weights = {"ACAV100M_sample": 1024, "adversarial_negative": 50, "positive": 50}

    config_path = _write_config(
        output_dir / "custom_model.yml",
        model_name=args.model_name,
        target_phrase=target,
        output_dir=output_dir,
        feature_data_files=feature_files,
        feature_weights=feature_weights,
        steps=args.steps,
    )
    command = [sys.executable, str(train_py), "--config", str(config_path)]
    print("config written to:", config_path)
    if args.no_train:
        print("training command:", " ".join(command))
        return 0
    print("training with:", " ".join(command))
    subprocess.run(command, check=True)
    onnx = output_dir / f"{args.model_name}.onnx"
    if not onnx.is_file():
        print(f"training finished but {onnx} not found; check the log", file=sys.stderr)
        return 3
    print(f"exported head: {onnx}")
    return 0


def _find_train_py() -> Path:
    try:
        import openwakeword
    except ImportError as exc:
        raise RuntimeError(
            "openwakeword is not installed; install it to train the EVIE head"
        ) from exc
    train_py = Path(openwakeword.__file__).resolve().parent / "train.py"
    if not train_py.is_file():
        raise SystemExit("openwakeword install has no train.py; upgrade the package")
    return train_py


def _iter_clips(directory: Path, suffixes=(".wav", ".flac", ".mp3")) -> list[Path]:
    if not directory.is_dir():
        raise SystemExit(f"clip directory not found: {directory}")
    return [p for p in directory.rglob("*") if p.suffix.lower() in suffixes]


if __name__ == "__main__":
    raise SystemExit(main())
