"""Encrypted backup, verification, and restore for the EV data store.

Backups are single encrypted JSON files with an ``ev.backup.v1`` envelope:

- The plaintext bundle contains the immutable event log, attachment metadata,
  registered devices, the access log, and the derived-memory snapshot (so a
  restore drill can verify counts and content equivalence).
- The bundle is authenticated-encrypted with Fernet using a key derived with
  scrypt from a **user-held passphrase** (the same KDF used for voiceprints).
- A SHA-256 of the canonical plaintext is stored in the envelope, so tampering
  is detected before any restore can proceed.
- Restore is event-sourced: raw events are re-inserted (deduplicated by content
  hash) and every derived memory/entity/relationship/conflict is regenerated by
  ``rebuild_derived_state``, matching the import path.

The backup passphrase is deliberately separate from ``EV_MASTER_KEY``: a leaked
database or master key does not decrypt old backups, and vice versa.
"""

from __future__ import annotations

import base64
import contextlib
import hashlib
import json
import os
from datetime import UTC, datetime
from pathlib import Path
from uuid import UUID

from sqlalchemy import delete, inspect, select, update
from sqlalchemy.ext.asyncio import AsyncSession

from app.config import settings
from app.models import (
    AccessLog,
    ApprovedAction,
    Attachment,
    Conflict,
    ConversationRollup,
    DecisionOutcome,
    Device,
    Entity,
    EntityRelationship,
    Event,
    FleetTask,
    MakerProject,
    Memory,
    MemoryEntity,
    MemoryEvent,
    PasskeyCredential,
    RecognitionLog,
    ResearchNote,
    ReVerificationProof,
    RoutineRun,
    RuntimeEvent,
    RuntimeHeartbeat,
    RuntimeSession,
    VoiceAttemptLog,
    VoiceSession,
)
from app.services.rebuild import rebuild_derived_state
from app.storage.object_store import get_object_store
from app.utils.text import utcnow
from app.voice.security import decrypt_payload, encrypt_payload

BACKUP_SCHEMA = "ev.backup.v1"
MIN_PASSPHRASE_LENGTH = 8


class BackupError(ValueError):
    """Raised for corrupt, tampered, or unreadable backups."""


def _canonical_plaintext(payload: dict) -> bytes:
    return json.dumps(
        payload,
        sort_keys=True,
        separators=(",", ":"),
        default=str,
    ).encode("utf-8")


def _json_safe(value):
    if isinstance(value, UUID):
        return str(value)
    if isinstance(value, datetime):
        return value.isoformat()
    if isinstance(value, (set, tuple)):
        return [_json_safe(item) for item in value]
    if isinstance(value, list):
        return [_json_safe(item) for item in value]
    if isinstance(value, dict):
        return {key: _json_safe(item) for key, item in value.items()}
    return value


def _row_dict(row) -> dict:
    """Serialize one ORM row to JSON-safe primitives."""
    return {
        attr.key: _json_safe(getattr(row, attr.key))
        for attr in inspect(row).mapper.column_attrs
    }


def _parse_dt(value) -> datetime | None:
    if value is None:
        return None
    parsed = value if isinstance(value, datetime) else datetime.fromisoformat(str(value))
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=UTC)
    return parsed


async def _collect_payload(session: AsyncSession) -> dict:
    async def rows(model):
        result = await session.execute(
            select(model).order_by(*model.__table__.primary_key.columns)
        )
        return list(result.scalars().all())

    events = await rows(Event)
    memories = await rows(Memory)
    entities = await rows(Entity)
    relationships = await rows(EntityRelationship)
    conflicts = await rows(Conflict)
    memory_events = await rows(MemoryEvent)
    memory_entities = await rows(MemoryEntity)
    attachments = await rows(Attachment)
    devices = await rows(Device)
    access_log = await rows(AccessLog)
    store = get_object_store()
    attachment_blobs: list[dict] = []
    for attachment in attachments:
        entry = _row_dict(attachment)
        with contextlib.suppress(Exception):
            blob = await store.get(attachment.storage_key)
            entry["blob_b64"] = base64.b64encode(blob).decode("ascii")
        attachment_blobs.append(entry)
    payload = {
        "schema": BACKUP_SCHEMA,
        "exported_at": utcnow().isoformat(),
        "events": [_row_dict(e) for e in events],
        "memories": [_row_dict(m) for m in memories],
        "entities": [_row_dict(e) for e in entities],
        "relationships": [_row_dict(r) for r in relationships],
        "conflicts": [_row_dict(c) for c in conflicts],
        "memory_events": [_row_dict(r) for r in memory_events],
        "memory_entities": [_row_dict(r) for r in memory_entities],
        "attachments": attachment_blobs,
        "devices": [_row_dict(d) for d in devices],
        "access_log": [_row_dict(a) for a in access_log],
        "counts": {
            "events": len(events),
            "memories": len(memories),
            "entities": len(entities),
            "relationships": len(relationships),
            "conflicts": len(conflicts),
            "attachments": len(attachments),
            "devices": len(devices),
            "access_log": len(access_log),
        },
    }
    return payload


def _default_backup_path() -> Path:
    directory = Path(settings.storage_root) / "backups"
    directory.mkdir(parents=True, exist_ok=True)
    stamp = utcnow().strftime("%Y%m%dT%H%M%S")
    return directory / f"ev-backup-{stamp}.evbackup"


async def create_backup(
    session: AsyncSession,
    *,
    passphrase: str,
    destination: str | None = None,
) -> dict:
    """Encrypt and write a full backup bundle. Returns file metadata."""
    if len(passphrase) < MIN_PASSPHRASE_LENGTH:
        raise BackupError(
            f"Backup passphrase must be at least {MIN_PASSPHRASE_LENGTH} characters"
        )
    payload = await _collect_payload(session)
    plaintext = _canonical_plaintext(payload)
    ciphertext, salt = encrypt_payload(payload, master_key=passphrase)
    # P0 PART 3: backups carry lineage metadata (explicit STATE_EPOCH +
    # environment). The epoch recorded here is the SOURCE lineage at backup
    # time; a later restore still rotates to a NEW active epoch.
    from app.ops.state_epoch import envelope_metadata, get_current_epoch_id

    source_epoch = await get_current_epoch_id(session)
    envelope = {
        "schema": BACKUP_SCHEMA,
        "created_at": utcnow().isoformat(),
        "ciphertext": ciphertext,
        "salt": salt,
        "plaintext_sha256": hashlib.sha256(plaintext).hexdigest(),
        "counts": payload["counts"],
        **envelope_metadata(
            source_epoch,
            __import__("os").environ.get("EV_ENV"),
        ),
    }
    path = Path(destination) if destination else _default_backup_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(envelope, sort_keys=True, separators=(",", ":")),
        encoding="utf-8",
    )
    os.chmod(path, 0o600)
    return {
        "path": str(path),
        "schema": BACKUP_SCHEMA,
        "created_at": envelope["created_at"],
        "checksum": envelope["plaintext_sha256"],
        "size_bytes": path.stat().st_size,
        "counts": envelope["counts"],
    }


def _read_envelope(path: str) -> dict:
    file_path = Path(path)
    if not file_path.exists() or not file_path.is_file():
        raise BackupError(f"Backup file not found: {path}")
    try:
        envelope = json.loads(file_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise BackupError(f"Backup file is not valid JSON: {path}") from exc
    if envelope.get("schema") != BACKUP_SCHEMA:
        raise BackupError(f"Unsupported backup schema: {envelope.get('schema')}")
    if not envelope.get("ciphertext") or not envelope.get("salt"):
        raise BackupError("Backup envelope is missing ciphertext or salt")
    return envelope


def verify_backup(path: str, passphrase: str) -> dict:
    """Decrypt and integrity-check a backup file without touching the database."""
    envelope = _read_envelope(path)
    try:
        payload = decrypt_payload(
            envelope["ciphertext"],
            envelope["salt"],
            master_key=passphrase,
        )
    except ValueError as exc:
        return {
            "valid": False,
            "schema": envelope["schema"],
            "created_at": envelope.get("created_at"),
            "counts": envelope.get("counts") or {},
            "checksum_match": False,
            "reason": str(exc),
        }
    expected = envelope.get("plaintext_sha256")
    actual = hashlib.sha256(_canonical_plaintext(payload)).hexdigest()
    checksum_match = bool(expected) and expected == actual
    if not checksum_match:
        return {
            "valid": False,
            "schema": envelope["schema"],
            "created_at": envelope.get("created_at"),
            "counts": envelope.get("counts") or {},
            "checksum_match": False,
            "reason": "Plaintext checksum mismatch: backup is corrupt or tampered",
        }
    return {
        "valid": True,
        "schema": envelope["schema"],
        "created_at": envelope.get("created_at"),
        "counts": payload.get("counts") or {},
        "checksum_match": True,
        "reason": None,
    }


def load_backup(path: str, passphrase: str) -> dict:
    """Return the decrypted, integrity-checked backup payload."""
    result = verify_backup(path, passphrase)
    if not result["valid"]:
        raise BackupError(result["reason"] or "Backup verification failed")
    envelope = _read_envelope(path)
    return decrypt_payload(
        envelope["ciphertext"],
        envelope["salt"],
        master_key=passphrase,
    )


async def _delete_voice_replay_nonces(session: AsyncSession) -> None:
    from sqlalchemy import text as _text

    await session.execute(_text("DELETE FROM voice_replay_nonces WHERE session_id IS NOT NULL"))


async def _wipe_data_tables(session: AsyncSession) -> None:
    """Delete the personal-data layer and its dependent operational rows."""
    # Operational rows that reference devices/events/memories first.
    await session.execute(delete(RuntimeEvent))
    await session.execute(delete(RoutineRun))
    await session.execute(delete(ApprovedAction))
    await session.execute(delete(PasskeyCredential))
    await session.execute(delete(ReVerificationProof))
    # Additional voice_session FK children (re-verification tickets,
    # attempt log, replay nonces) must clear before their parent.
    await session.execute(delete(ReVerificationProof))
    await session.execute(delete(VoiceAttemptLog))
    await _delete_voice_replay_nonces(session)
    await session.execute(delete(VoiceSession))
    await session.execute(delete(RuntimeHeartbeat))
    await session.execute(delete(RuntimeSession))
    await session.execute(delete(FleetTask))
    await session.execute(delete(RecognitionLog))
    await session.execute(delete(ResearchNote))
    await session.execute(delete(ConversationRollup))

    # Detach operational rows that reference derived memory.
    await session.execute(
        update(DecisionOutcome).values(decision_memory_id=None, lesson_memory_id=None)
    )
    await session.execute(update(MakerProject).values(goal_memory_id=None))

    # Derived layer.
    await session.execute(delete(MemoryEntity))
    await session.execute(delete(MemoryEvent))
    await session.execute(delete(Conflict))
    await session.execute(delete(EntityRelationship))
    await session.execute(delete(Memory))
    await session.execute(delete(Entity))

    # Primary stores.
    await session.execute(delete(Attachment))
    await session.execute(delete(AccessLog))
    await session.execute(delete(Device))
    await session.execute(delete(Event))


async def _restore_event(
    session: AsyncSession,
    data: dict,
    *,
    existing_hashes: set[str],
) -> bool:
    sha256 = str(data["sha256"])
    if sha256 in existing_hashes:
        return False
    session.add(
        Event(
            id=UUID(str(data["id"])),
            occurred_at=_parse_dt(data["occurred_at"]) or utcnow(),
            ingested_at=_parse_dt(data["ingested_at"]) or utcnow(),
            source=str(data["source"]),
            event_type=str(data["event_type"]),
            content=data.get("content") or {},
            metadata_=data.get("metadata") or {},
            device_id=data.get("device_id"),
            conversation_id=(
                UUID(str(data["conversation_id"])) if data.get("conversation_id") else None
            ),
            privacy_level=str(data.get("privacy_level") or "normal"),
            sha256=sha256,
            tombstoned_at=_parse_dt(data.get("tombstoned_at")),
            tombstone_reason=data.get("tombstone_reason"),
        )
    )
    existing_hashes.add(sha256)
    return True


async def restore_backup(
    session: AsyncSession,
    *,
    path: str,
    passphrase: str,
    mode: str = "merge",
    confirm_wipe: bool = False,
    actor: str = "master",
) -> dict:
    """Restore a verified backup.

    ``mode="merge"`` inserts missing events and rebuilds derived state.
    ``mode="wipe"`` clears the personal-data layer first (a genuine restore
    drill) and requires ``confirm_wipe=True``.
    """
    payload = load_backup(path, passphrase)
    if payload.get("schema") != BACKUP_SCHEMA:
        raise BackupError(f"Unsupported backup schema: {payload.get('schema')}")
    if mode not in ("merge", "wipe"):
        raise BackupError(f"Unsupported restore mode: {mode}")
    if mode == "wipe" and not confirm_wipe:
        raise BackupError("wipe mode requires confirm_wipe=true")

    if mode == "wipe":
        await _wipe_data_tables(session)

    existing_hashes = set(
        (await session.execute(select(Event.sha256))).scalars().all()
    )
    events_restored = 0
    for data in payload.get("events", []):
        if await _restore_event(session, data, existing_hashes=existing_hashes):
            events_restored += 1
    await session.flush()

    existing_ids = {
        str(row[0])
        for row in (await session.execute(select(Device.id))).all()
    }
    devices_restored = 0
    for data in payload.get("devices", []):
        device_id = str(data["id"])
        if device_id in existing_ids:
            continue
        session.add(
            Device(
                id=UUID(device_id),
                name=str(data.get("name") or "restored"),
                token_hash=data.get("token_hash"),
                created_at=_parse_dt(data.get("created_at")) or utcnow(),
                last_seen_at=_parse_dt(data.get("last_seen_at")),
                revoked_at=_parse_dt(data.get("revoked_at")),
                capabilities=data.get("capabilities") or [],
            )
        )
        existing_ids.add(device_id)
        devices_restored += 1

    existing_attachment_ids = {
        str(row[0])
        for row in (await session.execute(select(Attachment.id))).all()
    }
    attachments_restored = 0
    restored_blobs = 0
    store = get_object_store()
    for data in payload.get("attachments", []):
        attachment_id = str(data["id"])
        if attachment_id in existing_attachment_ids:
            continue
        storage_key = str(data.get("storage_key") or "")
        session.add(
            Attachment(
                id=UUID(attachment_id),
                event_id=UUID(str(data["event_id"])),
                filename=str(data.get("filename") or "unnamed"),
                content_type=data.get("content_type"),
                size_bytes=int(data.get("size_bytes") or 0),
                storage_key=storage_key,
                sha256=str(data.get("sha256") or ""),
                created_at=_parse_dt(data.get("created_at")) or utcnow(),
            )
        )
        if data.get("blob_b64") and storage_key:
            with contextlib.suppress(Exception):
                await store.put(
                    storage_key,
                    base64.b64decode(str(data["blob_b64"])),
                    data.get("content_type"),
                )
                restored_blobs += 1
        existing_attachment_ids.add(attachment_id)
        attachments_restored += 1

    existing_access_ids = {
        str(row[0]) for row in (await session.execute(select(AccessLog.id))).all()
    }
    access_restored = 0
    for data in payload.get("access_log", []):
        access_id = str(data["id"])
        if access_id in existing_access_ids:
            continue
        session.add(
            AccessLog(
                id=UUID(access_id),
                occurred_at=_parse_dt(data.get("occurred_at")) or utcnow(),
                actor=str(data.get("actor") or "restored"),
                action=str(data.get("action") or "restore"),
                endpoint=data.get("endpoint"),
                resource_type=data.get("resource_type"),
                resource_ids=data.get("resource_ids") or [],
                request_id=data.get("request_id"),
                details=data.get("details") or {},
            )
        )
        existing_access_ids.add(access_id)
        access_restored += 1

    await session.flush()
    rebuild = await rebuild_derived_state(
        session,
        actor=actor,
        reason=f"backup:restore:{mode}",
    )
    # P0 STATE EPOCH LAW: a lineage-replacing restore rotates the epoch in
    # the SAME transaction as the replacing write. 'new state + old epoch'
    # is impossible; if the restore fails, no rotation is advertised.
    from app.ops.state_epoch import rotate_epoch

    new_epoch = await rotate_epoch(
        session,
        reason=(
            f"backup.restore:{mode}:{Path(path).name}"
        ),
    )
    return {
        "mode": mode,
        "restored_at": utcnow().isoformat(),
        "new_state_epoch": new_epoch,
        "events_restored": events_restored,
        "events_skipped": max(0, len(payload.get("events", [])) - events_restored),
        "attachments_restored": attachments_restored,
        "blobs_restored": restored_blobs,
        "devices_restored": devices_restored,
        "access_log_restored": access_restored,
        "backup_counts": payload.get("counts") or {},
        "rebuild": rebuild,
    }
