"""Import/restore: rehydrate the immutable event log from an export bundle.

Import is event-sourced by design: only raw events are inserted (deduplicated by
content hash), and every derived memory, entity, relationship, conflict, pattern,
correction, and redaction is regenerated by replaying the log through the same
pipeline as ``rebuild_derived_state``. Raw events already in the store are never
overwritten or deleted; ``replace`` mode is therefore only allowed against an
empty event log (a fresh restore), never as an in-place destructive wipe.
"""

from __future__ import annotations

from datetime import UTC

from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models import Event
from app.schemas import ExportBundle
from app.services.access_log import log_access
from app.services.rebuild import rebuild_derived_state
from app.utils.text import canonical_json, sha256_hex


def _canonical_hash(event_data) -> str:
    occurred_at = event_data.occurred_at
    if occurred_at.tzinfo is None:
        occurred_at = occurred_at.replace(tzinfo=UTC)
    canonical = canonical_json(
        {
            "content": event_data.content,
            "metadata": event_data.metadata,
            "source": event_data.source,
            "event_type": event_data.event_type,
            "occurred_at": occurred_at.astimezone(UTC).replace(tzinfo=None).isoformat(),
            "privacy_level": event_data.privacy_level,
        }
    )
    return sha256_hex(canonical)


async def import_bundle(
    session: AsyncSession,
    bundle: ExportBundle,
    *,
    mode: str = "merge",
    actor: str = "master",
    request_id: str | None = None,
) -> dict:
    """Import raw events and rebuild all derived state from them."""
    if bundle.version != "1.0":
        raise ValueError(f"Unsupported export bundle version: {bundle.version}")
    if mode not in ("merge", "replace"):
        raise ValueError(f"Unsupported import mode: {mode}")

    existing_hashes = set((await session.execute(select(Event.sha256))).scalars().all())

    if mode == "replace":
        live = (
            await session.execute(
                select(func.count())
                .select_from(Event)
                .where(Event.tombstoned_at.is_(None))
            )
        ).scalar_one()
        if live:
            raise ValueError(
                "replace mode requires an empty event log; use merge, or restore into a fresh database"
            )

    imported = 0
    skipped = 0
    for event_data in bundle.events:
        if event_data.sha256 in existing_hashes:
            skipped += 1
            continue
        if _canonical_hash(event_data) != event_data.sha256:
            raise ValueError(f"Event hash mismatch for {event_data.id}: bundle is corrupt or tampered")
        session.add(
            Event(
                id=event_data.id,
                occurred_at=event_data.occurred_at,
                ingested_at=event_data.ingested_at,
                source=event_data.source,
                event_type=event_data.event_type,
                content=event_data.content,
                metadata_=event_data.metadata,
                device_id=event_data.device_id,
                conversation_id=event_data.conversation_id,
                privacy_level=event_data.privacy_level,
                sha256=event_data.sha256,
                tombstoned_at=event_data.tombstoned_at,
                tombstone_reason=event_data.tombstone_reason,
            )
        )
        imported += 1
        existing_hashes.add(event_data.sha256)
    await session.flush()

    report = await rebuild_derived_state(
        session,
        actor=actor,
        reason=f"import:{mode}",
        request_id=request_id,
    )
    await log_access(
        session,
        actor=actor,
        action="import",
        endpoint="POST /v1/import",
        resource_type="event",
        resource_ids=[],
        request_id=request_id,
        details={"mode": mode, "events_imported": imported, "events_skipped": skipped},
    )
    return {
        "mode": mode,
        "events_imported": imported,
        "events_skipped": skipped,
        **report,
    }
