"""Continuous living sensory daemon for EV (Evie).

MAC HUB ONLY. Do not edit this file for iPhone / PWA / device-gateway work.

The Mac is the continuity hub. iCloud + SMS/call forwarding already copy
owner life onto this machine. This follower reads those local copies:

- iMessage / SMS: ``~/Library/Messages/chat.db``
- WhatsApp Desktop: ``ChatStorage.sqlite`` (plaintext ZTEXT on this Mac)
- Call History: ``CallHistory.storedata`` (Continuity / iPhone forwarding)
- Apple Contacts / Mail envelopes / Google Calendar / health snapshots
- Photos library filenames (no pixels)

Rows are stored as events and opened only when recall chooses that shelf.
They are never written into live_context. Writes go through the helper
(Messages/Mail AppleScript, WhatsApp URL compose, call.place). Direct
edits of Apple/WhatsApp sqlite files are never used — they would not
sync and can corrupt the apps.
"""

from __future__ import annotations

import contextlib
import json
import logging
import os
import re
import sqlite3
import time
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Any

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.schemas import EventCreate
from app.services.event_service import EventService
from app.utils.text import utcnow

logger = logging.getLogger("ev.life_stream_daemon")

# Apple Cocoa reference date is 2001-01-01 00:00:00 UTC
APPLE_EPOCH = datetime(2001, 1, 1, 0, 0, 0, tzinfo=UTC)
_MAX_CONTACT_FPS = 5000
_ACCOUNT_PULL_SECONDS = 300
_LIVE_CATCHUP = 200
_HEALTH_METRIC_KEYS = (
    "sleep_hours",
    "hrv",
    "hrv_ms",
    "heart_rate",
    "resting_hr",
    "steps",
)
_BG_LAUNCH_COOLDOWN_S = 60.0
_last_bg_launch: dict[str, float] = {}


def life_stream_should_run() -> bool:
    """True when the owner opted into the headless follower.

    CI stays off (default provider=local, empty helper). A real Mac with
    ``EV_MESSAGING_PROVIDER=macos_life`` and a helper path auto-enables.
    """
    from app.config import settings

    if bool(getattr(settings, "life_stream_enabled", False)):
        return True
    provider = (getattr(settings, "messaging_provider", "local") or "local").strip().lower()
    helper = (getattr(settings, "life_helper_path", "") or "").strip()
    return provider == "macos_life" and bool(helper)


def _contact_fingerprint(contact: dict) -> str:
    phone = contact.get("phone") or ""
    if not phone and contact.get("phone_numbers"):
        numbers = contact.get("phone_numbers") or []
        phone = numbers[0] if numbers else ""
    email = contact.get("email") or ""
    if not email and contact.get("email_addresses"):
        addresses = contact.get("email_addresses") or []
        email = addresses[0] if addresses else ""
    return "|".join(
        [
            str(contact.get("id") or ""),
            str(contact.get("name") or contact.get("full_name") or ""),
            str(phone),
            str(email),
        ]
    )


def _apple_timestamp_to_datetime(raw_value: int | float | None) -> datetime:
    """Convert Apple CoreData/Cocoa timestamp to timezone-aware UTC datetime."""
    if raw_value is None or raw_value == 0:
        return utcnow()
    raw = float(raw_value)
    # Modern macOS chat.db stores nanoseconds since 2001; older versions stored seconds
    seconds = raw / 1_000_000_000.0 if abs(raw) > 1_000_000_000_000.0 else raw
    try:
        return APPLE_EPOCH + timedelta(seconds=seconds)
    except (OverflowError, OSError, ValueError):
        return utcnow()


def _mail_received_iso(raw_value: Any) -> str | None:
    if isinstance(raw_value, str) and raw_value.strip():
        return raw_value.strip()
    if not isinstance(raw_value, (int, float)):
        return None
    value = float(raw_value)
    try:
        if abs(value) > 1_000_000_000:
            occurred = datetime.fromtimestamp(value, tz=UTC)
        else:
            occurred = _apple_timestamp_to_datetime(value)
    except (OverflowError, OSError, ValueError):
        return None
    return occurred.isoformat()


def _sqlite_readable(path: str | None) -> bool:
    return bool(path) and os.path.isfile(path) and os.access(path, os.R_OK)


def find_mail_envelope_index() -> str:
    """Newest Apple Mail Envelope Index on this Mac, or empty."""
    root = os.path.expanduser("~/Library/Mail")
    if not os.path.isdir(root):
        return ""
    versions: list[tuple[int, str]] = []
    try:
        names = os.listdir(root)
    except OSError:
        return ""
    for name in names:
        if not name.startswith("V"):
            continue
        try:
            versions.append((int(name[1:]), name))
        except ValueError:
            continue
    versions.sort(reverse=True)
    for _, name in versions:
        path = os.path.join(root, name, "MailData", "Envelope Index")
        if _sqlite_readable(path):
            return path
    return ""


def _mac_app_running(*names: str) -> bool:
    """True when any of the app process names is running. No windows touched."""
    import subprocess

    for name in names:
        try:
            proc = subprocess.run(
                ["pgrep", "-x", name],
                capture_output=True,
                timeout=3,
            )
            if proc.returncode == 0 and (proc.stdout or b"").strip():
                return True
        except Exception:
            continue
    return False


def _db_mtime_age(path: str | None) -> float | None:
    """Seconds since the sqlite file changed. None when missing.

    Apple databases run in WAL mode: new messages land in -wal/-shm while
    the main file sits untouched for hours. Newest of the three is the truth.
    """
    if not path or not os.path.isfile(path):
        return None
    newest: float | None = None
    for candidate in (path, f"{path}-wal", f"{path}-shm"):
        try:
            if not os.path.isfile(candidate):
                continue
            mtime = os.path.getmtime(candidate)
            newest = mtime if newest is None else max(newest, mtime)
        except OSError:
            continue
    if newest is None:
        return None
    return max(0.0, time.time() - newest)


def ensure_background_sync(*, stale_after_seconds: float = 1800.0) -> dict[str, Any]:
    """Launch WhatsApp/Mail hidden when they are not running.

    Hidden background launch (``open -jg``): no windows, no focus steal.
    A quit app cannot ingest new messages, so we relaunch even if the
    sqlite copy looks recent. ``stale_after_seconds`` is unused for the
    launch gate (kept so callers stay source-compatible).
    """
    import subprocess

    # Call-site compatibility: a quit app is always stale for incoming mail/chats.
    _ = stale_after_seconds
    outcome: dict[str, Any] = {"checked": [], "launched": []}
    if not life_stream_should_run():
        return outcome
    try:
        from app.services.life_stream_daemon import get_life_stream_daemon

        daemon = get_life_stream_daemon()
    except Exception:
        return outcome
    with contextlib.suppress(Exception):
        daemon.refresh_mail_index_path()
    targets = [
        {
            "key": "whatsapp",
            "path": getattr(daemon, "whatsapp_db_path", ""),
            "procs": ("WhatsApp",),
            "app": "/Applications/WhatsApp.app",
        },
        {
            "key": "mail",
            "path": getattr(daemon, "mail_index_path", ""),
            "procs": ("Mail",),
            "app": "/System/Applications/Mail.app",
        },
    ]
    now = time.time()
    for target in targets:
        key = str(target["key"])
        outcome["checked"].append(key)
        if _mac_app_running(*target["procs"]):  # type: ignore[arg-type]
            continue
        last = _last_bg_launch.get(key, 0.0)
        if now - last < _BG_LAUNCH_COOLDOWN_S:
            continue
        app_path = str(target["app"])
        if not os.path.isdir(app_path):
            continue
        try:
            subprocess.run(
                ["open", "-jg", app_path],
                capture_output=True,
                timeout=10,
            )
            _last_bg_launch[key] = now
            outcome["launched"].append(key)
            age = _db_mtime_age(str(target["path"] or ""))
            logger.info(
                "Background sync: launched %s hidden (app was not running, db age %s)",
                key,
                f"{age:.0f}s" if age is not None else "unknown",
            )
        except Exception:
            continue
    return outcome


def life_freshness() -> dict[str, Any]:
    """One-shot sync health for spoken diagnostics. Never raises."""
    try:
        from app.services.life_stream_daemon import get_life_stream_daemon

        daemon = get_life_stream_daemon()
    except Exception:
        return {"ok": False, "reason": "daemon_unavailable"}
    with contextlib.suppress(Exception):
        daemon.refresh_mail_index_path()
    wa_path = getattr(daemon, "whatsapp_db_path", "")
    mail_path = getattr(daemon, "mail_index_path", "")
    chat_path = getattr(daemon, "chat_db_path", "")
    return {
        "ok": True,
        "whatsapp": {
            "readable": _sqlite_readable(wa_path),
            "mtime_age_s": _db_mtime_age(wa_path),
            "app_running": _mac_app_running("WhatsApp"),
        },
        "mail": {
            "readable": _sqlite_readable(mail_path),
            "mtime_age_s": _db_mtime_age(mail_path),
            "app_running": _mac_app_running("Mail"),
        },
        "imessage": {
            "readable": _sqlite_readable(chat_path),
            "mtime_age_s": _db_mtime_age(chat_path),
        },
    }


def _sqlite_query(path: str, sql: str, params: tuple = ()) -> list[tuple]:
    uri = f"file:{os.path.abspath(path)}?mode=ro"
    last: Exception | None = None
    for attempt in range(3):
        try:
            conn = sqlite3.connect(uri, uri=True, timeout=5.0)
            try:
                cursor = conn.cursor()
                cursor.execute(sql, params)
                return list(cursor.fetchall())
            finally:
                conn.close()
        except sqlite3.OperationalError as exc:
            last = exc
            # Locked/busy when Mail/WhatsApp/Messages vacuum — back off and retry.
            if "locked" not in str(exc).lower() and "busy" not in str(exc).lower():
                raise
            time.sleep(0.25 * (attempt + 1))
        except Exception:
            raise
    if last is not None:
        raise last
    return []


def _sqlite_scalar(path: str, sql: str, params: tuple = ()) -> Any:
    rows = _sqlite_query(path, sql, params)
    if not rows:
        return None
    return rows[0][0]


def _is_whatsapp_system_body(body: str) -> bool:
    """True for non-chat ZTEXT: bare JIDs, group invites, media refs."""
    text = (body or "").strip()
    if not text:
        return True
    if len(text) > 120:
        return False
    lowered = text.lower()
    # Bare JID like 107065062195290@lid or 120363...@g.us
    if "@lid" in lowered or "@g.us" in lowered or "@c.us" in lowered:
        compact = "".join(ch for ch in lowered if ch.isalnum() or ch in {"@", ".", "-", "_"})
        if len(compact) >= len(text.strip()) - 2:
            return True
    return False


def _is_whatsapp_broadcast_channel(sess_type: object, *jids: object) -> bool:
    """Status, Channels/newsletters, and broadcast lists are not chats."""
    try:
        if int(sess_type or 0) in {3, 5}:
            return True
    except (TypeError, ValueError):
        pass
    blob = " ".join(str(v or "") for v in jids).lower()
    return any(tag in blob for tag in ("@status", "@newsletter", "@broadcast"))


_PHONE_HANDLE_STRIP = dict.fromkeys(
    map(ord, "\u202a\u202b\u202c\u202d\u202e\u200e\u200f\xa0"), None
)


def _is_unnamed_phone_handle(handle: str) -> bool:
    """True for a digits-only WhatsApp partner (business ads, unsaved LID)."""
    raw = (handle or "").translate(_PHONE_HANDLE_STRIP).strip()
    if not raw:
        return False
    letters = re.sub(r"[^A-Za-z]", "", raw)
    digits = re.sub(r"\D", "", raw)
    return len(letters) < 2 and len(digits) >= 8


_TXN_SENDER_RE = re.compile(
    # Indian DLT headers survive mixed-case in Messages (ViCARE-S, ECIsms-G).
    # Two shapes: operator-PE (JD-ANKIAB) and PE-type (INVCPP-T, ViCARE-S).
    # Cap the suffix at 2 so hyphenated names (Mary-Jane) stay people.
    r"^[A-Za-z]{2}-[A-Za-z0-9]{5,6}$"
    r"|^[A-Za-z0-9]{2,6}-[A-Za-z0-9]{1,2}$"
    r"|^\d{3,6}$"  # numeric shortcodes: 56767, 121
    r"|^[A-Z0-9]{2,11}$",  # bare service headers: HDFCBK, INVCPP (all-caps, no spaces)
)
_TXN_BODY_RE = re.compile(
    r"\botp\b|one[\s-]?time (pass|password)|verification code|"
    r"\bcode\b.{0,12}\b(is|:)\b.{0,8}\d{4,8}|"
    r"\b(debited|credited)\b|a/c\b.{0,16}\b(x|xx|\*)|upi.{0,24}(ref|txn|transaction)|"
    r"\b(neft|imps|rtgs)\b|txn id|transaction id|"
    r"\b(account|card).{0,32}\b(rs\.?|inr|₹)\s?[\d,]+",
    re.IGNORECASE,
)


def _is_transactional_sms(body: str, handle: str) -> bool:
    """True for OTP / bank / service SMS that should not top a digest.

    iMessage handles are phone numbers, emails, or service headers — never
    bare first names. Service headers and shortcodes are transactional on
    sight; anyone else needs a strong OTP/bank signal in the body.
    """
    sender = (handle or "").strip()
    text = (body or "").strip()
    if not sender and not text:
        return False
    if sender and _TXN_SENDER_RE.match(sender):
        return True
    lowered_handle = sender.lower()
    if "@botplatform" in lowered_handle or lowered_handle.endswith(".jio"):
        return True
    if "evie-pair." in text.lower():
        return True
    if re.search(r"dear customer.{0,80}missed call", text, re.I):
        return True
    compact = text.strip()
    if compact in {"", "\ufffd", "￾"} or (
        len(compact) <= 2 and not any(ch.isalnum() for ch in compact)
    ):
        return True
    return bool(text) and bool(_TXN_BODY_RE.search(text))


_ROLE_LOCAL_RE = re.compile(
    r"^(no-?reply|no_reply|donotreply|do-not-reply|"
    r"mailer-daemon|mailerdaemon|postmaster|abuse|"
    r"notifications?|newsletters?|updates|marketing|support|billing|"
    r"news|hello|hi|hey|team|info|bounces?|unsubscribe)$",
    re.IGNORECASE,
)
_MAIL_ROLL_LABEL_RE = re.compile(
    r"^(mail|email|updates|news|smtp|bounce|bounces|m|em|send)$",
    re.IGNORECASE,
)
_FROM_BRAND_RE = re.compile(
    r"^[A-Za-z][\w.'-]+ from [A-Z]",
)
_FROM_ANGLE_RE = re.compile(r"^(?P<name>.*?)\s*<(?P<addr>[^>]+)>\s*$")


def _mail_from_parts(sender: str) -> tuple[str, str, str]:
    """Display name, local-part, domain — empty strings when missing."""
    text = " ".join(str(sender or "").split()).strip()
    if not text:
        return "", "", ""
    angled = _FROM_ANGLE_RE.match(text)
    if angled:
        display = (angled.group("name") or "").strip().strip('"')
        addr = (angled.group("addr") or "").strip()
    elif "@" in text and "<" not in text:
        display, addr = "", text
    else:
        return text, "", ""
    local, _, domain = addr.partition("@")
    return display, local.strip(), domain.strip().lower()


def _is_bulk_mail(sender: str, subject: str = "") -> bool:
    """True for one-way envelopes: role mailboxes, mail-roll hosts, brand From.

    Structural, not a brand list. `notifications@any.domain` is bulk;
    `Ada <ada@example.com>` is not. Subject is unused — topic words are
    not a reliable bulk signal.
    """
    del subject
    display, local, domain = _mail_from_parts(sender)
    if local and _ROLE_LOCAL_RE.match(local):
        return True
    label = domain.split(".", 1)[0] if domain else ""
    if label and _MAIL_ROLL_LABEL_RE.match(label):
        return True
    if display and _FROM_BRAND_RE.match(display):
        return True
    return False


def _mail_sender_in_contacts(sender: str, contacts: list[dict[str, Any]]) -> bool:
    """True when the envelope matches a stored person (email or full name)."""
    display, local, domain = _mail_from_parts(sender)
    addr = f"{local}@{domain}".lower() if local and domain else ""
    hay = f"{display} {addr}".strip().lower()
    if not hay:
        return False
    for row in contacts:
        if not isinstance(row, dict):
            continue
        email = str(row.get("email") or "").strip().lower()
        if email and email in hay:
            return True
        extra = row.get("email_addresses") or row.get("emails") or []
        if isinstance(extra, list):
            for item in extra:
                val = (
                    str(item.get("email") or "")
                    if isinstance(item, dict)
                    else str(item or "")
                ).strip().lower()
                if val and val in hay:
                    return True
        name = str(row.get("name") or row.get("full_name") or "").strip().lower()
        # Full name only — a lone first name collides with brands.
        if name and " " in name and name in hay:
            return True
    return False


def _group_per_person(hits: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Latest hit per handle, newest first. One loud thread can't flood a digest."""
    seen: set[str] = set()
    grouped: list[dict[str, Any]] = []
    for hit in hits:
        key = str(hit.get("handle") or "").strip().lower()
        if not key:
            key = str(hit.get("text") or "")[:48].lower()
        if key in seen:
            continue
        seen.add(key)
        grouped.append(hit)
    return grouped


def _filter_peek(rows: list[dict[str, Any]], tokens: list[str], limit: int) -> list[dict[str, Any]]:
    cap = max(1, min(int(limit or 8), 8))
    # The blob is lowercased — tokens must be too, or capitalized person
    # names ("Mansi") never match. Central fix for every peek caller.
    normalized = [
        str(token or "").strip().lower() for token in (tokens or []) if str(token or "").strip()
    ]
    if not normalized:
        return rows[:cap]
    scored: list[tuple[float, dict[str, Any]]] = []
    for row in rows:
        blob = " ".join(
            str(row.get(key) or "")
            for key in ("text", "gist", "subject", "sender")
        ).lower()
        hits = sum(1 for token in normalized if token and token in blob)
        if hits <= 0:
            continue
        item = dict(row)
        item["score"] = round(hits / len(normalized), 4)
        scored.append((hits / len(normalized), item))
    scored.sort(key=lambda item: item[0], reverse=True)
    return [item for _, item in scored[:cap]]


def health_snapshot_event_create(row: Any) -> EventCreate | None:
    """Compact health envelope. Metrics only; never dumped into chat."""
    if isinstance(row, dict):
        sid = str(row.get("id") or row.get("occurred_at") or "")
        readiness = row.get("readiness")
        metrics = row.get("metrics") if isinstance(row.get("metrics"), dict) else {}
        occurred = row.get("occurred_at")
    else:
        sid = str(getattr(row, "id", "") or "")
        readiness = getattr(row, "readiness", None)
        raw_metrics = getattr(row, "metrics", None)
        metrics = raw_metrics if isinstance(raw_metrics, dict) else {}
        occurred = getattr(row, "occurred_at", None)
    if not sid:
        return None
    bits = []
    if readiness is not None:
        bits.append(f"readiness {readiness}")
    compact: dict[str, Any] = {}
    for key in _HEALTH_METRIC_KEYS:
        value = metrics.get(key)
        if isinstance(value, (int, float)):
            compact[key] = value
            bits.append(f"{key} {value}")
    text = "Health: " + ", ".join(bits) if bits else "Health snapshot"
    return EventCreate(
        event_type="health.snapshot.recorded",
        source="health",
        content={"text": text, "readiness": readiness, "metrics": compact},
        occurred_at=occurred if occurred else None,
        privacy_level="sensitive",
        metadata={"source": "health_snapshot", "channel": "health", "snapshot_id": sid},
    )


class LifeStreamDaemon:
    """Headless sensory daemon for continuous background data observation."""

    def __init__(
        self,
        *,
        chat_db_path: str | None = None,
        last_message_rowid: int = 0,
        whatsapp_db_path: str | None = None,
        call_db_path: str | None = None,
        photos_db_path: str | None = None,
        mail_index_path: str | None = None,
    ) -> None:
        default_chat = os.path.expanduser("~/Library/Messages/chat.db")
        default_whatsapp = os.path.expanduser(
            "~/Library/Group Containers/group.net.whatsapp.WhatsApp.shared/ChatStorage.sqlite"
        )
        default_calls = os.path.expanduser(
            "~/Library/Application Support/CallHistoryDB/CallHistory.storedata"
        )
        default_photos = os.path.expanduser(
            "~/Pictures/Photos Library.photoslibrary/database/Photos.sqlite"
        )
        self.chat_db_path = default_chat if chat_db_path is None else chat_db_path
        # Isolated tests pass a temp chat.db. Do not also open the owner's
        # WhatsApp / CallHistory / Photos libraries unless those paths are set.
        use_real_hub = chat_db_path is None
        self.whatsapp_db_path = (
            default_whatsapp
            if whatsapp_db_path is None and use_real_hub
            else (whatsapp_db_path or "")
        )
        self.call_db_path = (
            default_calls
            if call_db_path is None and use_real_hub
            else (call_db_path or "")
        )
        self.photos_db_path = (
            default_photos
            if photos_db_path is None and use_real_hub
            else (photos_db_path or "")
        )
        self.mail_index_path = (
            find_mail_envelope_index()
            if mail_index_path is None and use_real_hub
            else (mail_index_path or "")
        )
        # Auto-resolved only: may be re-resolved when unreadable (Mail.app
        # upgrades move V10 -> V11; rebuilds briefly remove the file).
        # Explicitly-passed paths (tests) are never swapped for owner data.
        self._mail_index_auto = mail_index_path is None and use_real_hub
        self.last_message_rowid = last_message_rowid
        self.last_whatsapp_pk = 0
        self.last_call_pk = 0
        self.last_photo_pk = 0
        self._known_contact_ids: set[str] = set()
        self._contact_fps: dict[str, str] = {}
        self._mail_fps: dict[str, str] = {}
        self._calendar_fps: dict[str, str] = {}
        self._health_fps: dict[str, str] = {}
        self._last_account_pull: float = 0.0
        self._cursor_path: Path | None = None
        self._bootstrapped: set[str] = set()
        self._cached_contacts: list[dict[str, Any]] = []

    def remember_contacts(self, contacts: list[dict[str, Any]]) -> None:
        """Keep a short ask-time copy of the last helper address-book pull."""
        self._cached_contacts = [row for row in contacts if isinstance(row, dict)][:500]

    def is_chat_db_accessible(self) -> bool:
        """Return True if chat.db exists and is readable (Full Disk Access granted)."""
        return _sqlite_readable(self.chat_db_path)

    def refresh_mail_index_path(self) -> str:
        """Re-resolve the Envelope Index when the held path went stale.

        Never raises. Only applies to auto-resolved hubs; explicit test
        paths are left untouched so tests can't leak into owner Mail.
        """
        if not getattr(self, "_mail_index_auto", False):
            return self.mail_index_path
        if _sqlite_readable(self.mail_index_path):
            return self.mail_index_path
        try:
            found = find_mail_envelope_index()
        except Exception:
            return self.mail_index_path
        if found:
            self.mail_index_path = found
        return self.mail_index_path

    def _catchup_pk(self, attr: str, path: str, table: str, column: str = "Z_PK") -> int:
        """On first sight of a large DB, start near the live tail instead of year one."""
        current = int(getattr(self, attr) or 0)
        if current > 0 or attr in self._bootstrapped:
            return current
        self._bootstrapped.add(attr)
        if not _sqlite_readable(path):
            return 0
        try:
            max_pk = _sqlite_scalar(path, f"SELECT MAX({column}) FROM {table}")
        except Exception:  # noqa: BLE001 - missing table is a skip, not a crash
            return 0
        if not isinstance(max_pk, (int, float)) or max_pk is None:
            return 0
        start = max(0, int(max_pk) - _LIVE_CATCHUP)
        setattr(self, attr, start)
        return start

    async def _safe_sync(
        self,
        name: str,
        coro,
        session: AsyncSession | None = None,
    ) -> list[Any]:
        try:
            return await coro
        except Exception as exc:  # noqa: BLE001 - one stream must not skip the others
            logger.warning("life stream %s skipped: %s", name, type(exc).__name__)
            if session is not None:
                with contextlib.suppress(Exception):
                    await session.rollback()
            return []

    async def sync_imessage(
        self,
        session: AsyncSession,
        *,
        limit: int = 50,
    ) -> list[Any]:
        """Poll chat.db for messages newer than last_message_rowid and ingest them."""
        if not self.is_chat_db_accessible():
            logger.debug(
                "chat.db not accessible at '%s' (degraded or FDA missing)",
                self.chat_db_path,
            )
            return []

        events = []
        event_service = EventService(session, actor="life_stream_daemon")

        try:
            rows = _sqlite_query(
                self.chat_db_path,
                """
                    SELECT message.ROWID, message.date, message.text, handle.id, message.is_from_me
                    FROM message
                    LEFT JOIN handle ON message.handle_id = handle.ROWID
                    WHERE message.ROWID > ?
                    ORDER BY message.ROWID ASC
                    LIMIT ?
                """,
                (self.last_message_rowid, max(1, limit)),
            )
        except Exception as exc:
            logger.warning("Failed reading chat.db: %s", exc)
            return []

        # Cursor advances only after a successful commit. Advancing per-row
        # loses messages when commit fails (cursor ahead of stored events).
        seen_max = self.last_message_rowid
        for rowid, raw_date, raw_text, handle, is_from_me in rows:
            text = (raw_text or "").strip()
            if rowid > seen_max:
                seen_max = rowid
            if not text:
                continue

            occurred_at = _apple_timestamp_to_datetime(raw_date)
            sender_or_target = str(handle or "unknown").strip()
            from_me = bool(is_from_me)

            event_type = (
                "message.imessage.sent" if from_me else "message.imessage.received"
            )
            event_create = EventCreate(
                event_type=event_type,
                source="imessage",
                content={
                    "text": text,
                    "handle": sender_or_target,
                    "is_from_me": from_me,
                    "rowid": rowid,
                },
                occurred_at=occurred_at,
                privacy_level="sensitive",
                metadata={"source_rowid": rowid, "channel": "messages"},
            )

            created_event = await event_service.create(event_create)
            events.append(created_event)

        if events:
            await session.commit()
            self.last_message_rowid = seen_max
            logger.info("Ingested %d new iMessage events (latest rowid: %d)", len(events), self.last_message_rowid)
        elif seen_max > self.last_message_rowid:
            # All rows skipped (empty bodies): nothing written, safe to advance.
            self.last_message_rowid = seen_max

        return events

    async def sync_whatsapp(
        self,
        session: AsyncSession,
        *,
        limit: int = 50,
    ) -> list[Any]:
        """Poll WhatsApp Desktop ChatStorage.sqlite. Read-only; never write that file."""
        path = self.whatsapp_db_path
        if not _sqlite_readable(path):
            return []
        self._catchup_pk("last_whatsapp_pk", path, "ZWAMESSAGE")
        try:
            rows = _sqlite_query(
                path,
                """
                SELECT m.Z_PK, m.ZMESSAGEDATE, m.ZTEXT, m.ZISFROMME, m.ZFROMJID, m.ZTOJID,
                       m.ZPUSHNAME, s.ZPARTNERNAME, s.ZCONTACTJID, s.ZSESSIONTYPE
                FROM ZWAMESSAGE m
                LEFT JOIN ZWACHATSESSION s ON m.ZCHATSESSION = s.Z_PK
                WHERE m.Z_PK > ?
                  AND m.ZTEXT IS NOT NULL
                  AND trim(m.ZTEXT) != ''
                ORDER BY m.Z_PK ASC
                LIMIT ?
                """,
                (self.last_whatsapp_pk, max(1, limit)),
            )
        except sqlite3.OperationalError as exc:
            if "no such column" not in str(exc).lower():
                logger.warning("Failed reading WhatsApp ChatStorage: %s", type(exc).__name__)
                return []
            try:
                rows = _sqlite_query(
                    path,
                    """
                    SELECT m.Z_PK, m.ZMESSAGEDATE, m.ZTEXT, m.ZISFROMME, m.ZFROMJID, m.ZTOJID,
                           m.ZPUSHNAME, s.ZPARTNERNAME
                    FROM ZWAMESSAGE m
                    LEFT JOIN ZWACHATSESSION s ON m.ZCHATSESSION = s.Z_PK
                    WHERE m.Z_PK > ?
                      AND m.ZTEXT IS NOT NULL
                      AND trim(m.ZTEXT) != ''
                    ORDER BY m.Z_PK ASC
                    LIMIT ?
                    """,
                    (self.last_whatsapp_pk, max(1, limit)),
                )
                rows = [(*r, "", 0) for r in rows]
            except Exception as exc2:
                logger.warning("Failed reading WhatsApp ChatStorage: %s", type(exc2).__name__)
                return []
        except Exception as exc:
            logger.warning("Failed reading WhatsApp ChatStorage: %s", type(exc).__name__)
            return []

        events = []
        event_service = EventService(session, actor="life_stream_daemon")
        # Cursor advances only after a successful commit. Advancing per-row
        # loses messages when commit fails (cursor ahead of stored events).
        seen_max = self.last_whatsapp_pk
        for (
            pk,
            raw_date,
            raw_text,
            is_from_me,
            from_jid,
            to_jid,
            push_name,
            partner_name,
            contact_jid,
            sess_type,
        ) in rows:
            text = str(raw_text or "").strip()
            pk_i = int(pk or 0)
            if pk_i > seen_max:
                seen_max = pk_i
            if not text:
                continue
            if _is_whatsapp_broadcast_channel(sess_type, from_jid, to_jid, contact_jid):
                continue
            if _is_whatsapp_system_body(text):
                continue
            from_me = bool(is_from_me)
            who = str(partner_name or push_name or from_jid or to_jid or contact_jid or "someone").strip()
            event_create = EventCreate(
                event_type="message.whatsapp.sent" if from_me else "message.whatsapp.received",
                source="whatsapp",
                content={
                    "text": text,
                    "handle": who,
                    "is_from_me": from_me,
                    "pk": pk_i,
                },
                occurred_at=_apple_timestamp_to_datetime(raw_date),
                privacy_level="sensitive",
                metadata={"source_pk": pk_i, "channel": "whatsapp"},
            )
            events.append(await event_service.create(event_create))

        if events:
            await session.commit()
            self.last_whatsapp_pk = seen_max
            logger.info("Ingested %d WhatsApp events (latest pk: %d)", len(events), self.last_whatsapp_pk)
        elif seen_max > self.last_whatsapp_pk:
            # All rows skipped (status/system): nothing written, safe to advance.
            self.last_whatsapp_pk = seen_max
        return events

    async def sync_calls(
        self,
        session: AsyncSession,
        *,
        limit: int = 50,
    ) -> list[Any]:
        """Poll CallHistory.storedata copied here by Continuity / iPhone forwarding."""
        path = self.call_db_path
        if not _sqlite_readable(path):
            return []
        self._catchup_pk("last_call_pk", path, "ZCALLRECORD")
        try:
            rows = _sqlite_query(
                path,
                """
                SELECT Z_PK, ZDATE, ZDURATION, ZADDRESS, ZNAME, ZORIGINATED, ZANSWERED, ZCALLTYPE
                FROM ZCALLRECORD
                WHERE Z_PK > ?
                ORDER BY Z_PK ASC
                LIMIT ?
                """,
                (self.last_call_pk, max(1, limit)),
            )
        except Exception as exc:
            logger.warning("Failed reading CallHistory: %s", type(exc).__name__)
            return []

        events = []
        event_service = EventService(session, actor="life_stream_daemon")
        seen_max = self.last_call_pk
        for pk, raw_date, duration, address, name, originated, answered, call_type in rows:
            pk_i = int(pk or 0)
            if pk_i > seen_max:
                seen_max = pk_i
            outgoing = bool(originated)
            picked_up = bool(answered)
            direction = "outgoing" if outgoing else "incoming"
            status = "answered" if picked_up else "missed"
            who = str(name or address or "unknown").strip()
            seconds = int(duration or 0) if isinstance(duration, (int, float)) else 0
            text = f"{status} {direction} call {who}"
            if seconds > 0:
                text = f"{text} ({seconds}s)"
            event_create = EventCreate(
                event_type="call.history.recorded",
                source="calls",
                content={
                    "text": text,
                    "name": str(name or "").strip(),
                    "address": str(address or "").strip(),
                    "duration": seconds,
                    "originated": outgoing,
                    "answered": picked_up,
                    "call_type": call_type,
                    "pk": pk_i,
                },
                occurred_at=_apple_timestamp_to_datetime(raw_date),
                privacy_level="sensitive",
                metadata={"source_pk": pk_i, "channel": "calls"},
            )
            events.append(await event_service.create(event_create))

        if events:
            await session.commit()
            self.last_call_pk = seen_max
            logger.info("Ingested %d call-history events (latest pk: %d)", len(events), self.last_call_pk)
        elif seen_max > self.last_call_pk:
            self.last_call_pk = seen_max
        return events

    async def sync_photos(
        self,
        session: AsyncSession,
        *,
        limit: int = 50,
    ) -> list[Any]:
        """Index Photos library filenames. Never pixels, never directory paths."""
        path = self.photos_db_path
        if not _sqlite_readable(path):
            return []
        self._catchup_pk("last_photo_pk", path, "ZASSET")
        try:
            rows = _sqlite_query(
                path,
                """
                SELECT Z_PK, ZFILENAME, ZDATECREATED
                FROM ZASSET
                WHERE Z_PK > ?
                  AND ZFILENAME IS NOT NULL
                  AND trim(ZFILENAME) != ''
                  AND IFNULL(ZTRASHEDSTATE, 0) = 0
                ORDER BY Z_PK ASC
                LIMIT ?
                """,
                (self.last_photo_pk, max(1, limit)),
            )
        except Exception as exc:
            logger.warning("Failed reading Photos library: %s", type(exc).__name__)
            return []

        events = []
        event_service = EventService(session, actor="life_stream_daemon")
        seen_max = self.last_photo_pk
        for pk, filename, raw_date in rows:
            pk_i = int(pk or 0)
            if pk_i > seen_max:
                seen_max = pk_i
            name = str(filename or "").strip()
            if not name:
                continue
            event_create = EventCreate(
                event_type="photo.library.indexed",
                source="photos",
                content={"text": name, "filename": name, "pk": pk_i},
                occurred_at=_apple_timestamp_to_datetime(raw_date),
                privacy_level="sensitive",
                metadata={"source_pk": pk_i, "channel": "photos"},
            )
            events.append(await event_service.create(event_create))

        if events:
            await session.commit()
            self.last_photo_pk = seen_max
            logger.info("Ingested %d photo filename events (latest pk: %d)", len(events), self.last_photo_pk)
        elif seen_max > self.last_photo_pk:
            self.last_photo_pk = seen_max
        return events

    def peek_whatsapp(self, *, tokens: list[str] | None = None, limit: int = 8) -> list[dict[str, Any]]:
        """Read the live WhatsApp Desktop DB. No Event writes.

        Status broadcasts (ZSESSIONTYPE=3, *@status) and Channels
        (ZSESSIONTYPE=5, *@newsletter) are excluded — they are not chats.
        Ordered by message date for true recency.
        """
        path = self.whatsapp_db_path
        if not _sqlite_readable(path):
            return []
        try:
            rows = _sqlite_query(
                path,
                """
                SELECT m.Z_PK, m.ZMESSAGEDATE, m.ZTEXT, m.ZISFROMME,
                       m.ZPUSHNAME, s.ZPARTNERNAME, m.ZFROMJID, m.ZTOJID,
                       s.ZSESSIONTYPE, s.ZCONTACTJID
                FROM ZWAMESSAGE m
                LEFT JOIN ZWACHATSESSION s ON m.ZCHATSESSION = s.Z_PK
                WHERE m.ZTEXT IS NOT NULL AND trim(m.ZTEXT) != ''
                  AND IFNULL(s.ZSESSIONTYPE, 0) NOT IN (3, 5)
                  AND IFNULL(s.ZCONTACTJID, '') NOT LIKE '%@status%'
                  AND IFNULL(s.ZCONTACTJID, '') NOT LIKE '%@newsletter%'
                  AND IFNULL(s.ZCONTACTJID, '') NOT LIKE '%@broadcast%'
                  AND IFNULL(m.ZFROMJID, '') NOT LIKE '%@status%'
                  AND IFNULL(m.ZTOJID, '') NOT LIKE '%@status%'
                ORDER BY m.ZMESSAGEDATE DESC, m.Z_PK DESC
                LIMIT 200
                """,
            )
        except sqlite3.OperationalError as exc:
            if "no such column" not in str(exc).lower():
                logger.warning("WhatsApp live peek skipped", exc_info=False)
                return []
            # Minimal/legacy ChatStorage (tests, older Desktop): no ZSESSIONTYPE.
            try:
                rows = _sqlite_query(
                    path,
                    """
                    SELECT m.Z_PK, m.ZMESSAGEDATE, m.ZTEXT, m.ZISFROMME,
                           m.ZPUSHNAME, s.ZPARTNERNAME, m.ZFROMJID, m.ZTOJID
                    FROM ZWAMESSAGE m
                    LEFT JOIN ZWACHATSESSION s ON m.ZCHATSESSION = s.Z_PK
                    WHERE m.ZTEXT IS NOT NULL AND trim(m.ZTEXT) != ''
                      AND IFNULL(m.ZFROMJID, '') NOT LIKE '%@status%'
                      AND IFNULL(m.ZTOJID, '') NOT LIKE '%@status%'
                    ORDER BY m.ZMESSAGEDATE DESC, m.Z_PK DESC
                    LIMIT 200
                    """,
                )
                rows = [(*r, 0, "") for r in rows]
            except Exception:
                logger.warning("WhatsApp live peek skipped", exc_info=False)
                return []
        except Exception:
            logger.warning("WhatsApp live peek skipped", exc_info=False)
            return []
        hits: list[dict[str, Any]] = []
        for pk, raw_date, raw_text, is_from_me, push_name, partner_name, from_jid, to_jid, sess, cjid in rows:
            body = str(raw_text or "").strip()
            if not body:
                continue
            if _is_whatsapp_broadcast_channel(sess, from_jid, to_jid, cjid):
                continue
            # Skip system JID bodies (group invites, media refs) — not chat text.
            if _is_whatsapp_system_body(body):
                continue
            who = "You" if is_from_me else str(partner_name or push_name or from_jid or to_jid or "someone").strip()
            occurred = _apple_timestamp_to_datetime(raw_date)
            hits.append(
                {
                    "id": f"wa-live-{int(pk or 0)}",
                    "source": "whatsapp",
                    "when": occurred.isoformat(),
                    "text": f"{who}: {body}"[:400],
                    "handle": str(partner_name or push_name or from_jid or to_jid or "").strip(),
                    "preview": body[:220],
                    "kind": "live_mac",
                    "memory_type": "message.whatsapp.sent" if is_from_me else "message.whatsapp.received",
                    "confidence": "live_mac",
                    "score": 0.15,
                    "provenance": [f"wa-live-{int(pk or 0)}"],
                    "shelf": "chats",
                    "channel": "whatsapp",
                }
            )
        distinctive = [token for token in (tokens or []) if token]
        if not distinctive:
            # Digest: named people/groups, incoming first. Unsaved phone-number
            # ads and your own pings stay findable via a name/number search.
            incoming = [
                hit
                for hit in hits
                if str(hit.get("memory_type") or "") != "message.whatsapp.sent"
            ]
            pool = incoming or hits
            named = [
                hit
                for hit in pool
                if not _is_unnamed_phone_handle(str(hit.get("handle") or ""))
            ]
            unnamed = [
                hit
                for hit in pool
                if _is_unnamed_phone_handle(str(hit.get("handle") or ""))
            ]
            hits = _group_per_person(named) or _group_per_person(unnamed)
        return _filter_peek(hits, distinctive, limit)

    def read_whatsapp_person(self, token: str, *, limit: int = 800) -> list[dict[str, Any]]:
        """Ask-only: live WhatsApp lines whose partner name is that person."""

        compact = "".join(ch for ch in (token or "").lower() if ch.isalpha())
        if len(compact) < 2:
            return []
        path = self.whatsapp_db_path
        if not _sqlite_readable(path):
            return []
        cap = max(1, min(int(limit or 800), 2000))
        try:
            rows = _sqlite_query(
                path,
                """
                SELECT m.ZMESSAGEDATE, m.ZTEXT, m.ZISFROMME,
                       m.ZPUSHNAME, s.ZPARTNERNAME, m.ZFROMJID, m.ZTOJID,
                       s.ZSESSIONTYPE, s.ZCONTACTJID
                FROM ZWAMESSAGE m
                LEFT JOIN ZWACHATSESSION s ON m.ZCHATSESSION = s.Z_PK
                WHERE m.ZTEXT IS NOT NULL AND trim(m.ZTEXT) != ''
                  AND IFNULL(s.ZSESSIONTYPE, 0) NOT IN (3, 5)
                  AND IFNULL(s.ZCONTACTJID, '') NOT LIKE '%@status%'
                  AND IFNULL(s.ZCONTACTJID, '') NOT LIKE '%@newsletter%'
                  AND lower(
                    ifnull(s.ZPARTNERNAME, '') || ' ' || ifnull(m.ZPUSHNAME, '')
                  ) LIKE ?
                ORDER BY m.ZMESSAGEDATE DESC
                LIMIT ?
                """,
                (f"%{compact}%", cap),
            )
        except sqlite3.OperationalError as exc:
            if "no such column" not in str(exc).lower():
                logger.warning("WhatsApp person read skipped", exc_info=False)
                return []
            try:
                rows = _sqlite_query(
                    path,
                    """
                    SELECT m.ZMESSAGEDATE, m.ZTEXT, m.ZISFROMME,
                           m.ZPUSHNAME, s.ZPARTNERNAME, m.ZFROMJID, m.ZTOJID
                    FROM ZWAMESSAGE m
                    LEFT JOIN ZWACHATSESSION s ON m.ZCHATSESSION = s.Z_PK
                    WHERE m.ZTEXT IS NOT NULL AND trim(m.ZTEXT) != ''
                      AND lower(
                        ifnull(s.ZPARTNERNAME, '') || ' ' || ifnull(m.ZPUSHNAME, '')
                      ) LIKE ?
                    ORDER BY m.ZMESSAGEDATE DESC
                    LIMIT ?
                    """,
                    (f"%{compact}%", cap),
                )
                rows = [(*r, 0, "") for r in rows]
            except Exception:
                logger.warning("WhatsApp person read skipped", exc_info=False)
                return []
        except Exception:
            logger.warning("WhatsApp person read skipped", exc_info=False)
            return []
        out: list[dict[str, Any]] = []
        for raw_date, raw_text, is_from_me, push_name, partner_name, from_jid, to_jid, _sess, _cjid in rows:
            body = str(raw_text or "").strip()
            who = str(partner_name or push_name or from_jid or to_jid or "").strip()
            compact_who = "".join(ch for ch in who.lower() if ch.isalpha())
            if compact not in compact_who:
                continue
            if not body or _is_whatsapp_system_body(body):
                continue
            if _is_whatsapp_broadcast_channel(_sess, from_jid, to_jid, _cjid):
                continue
            out.append(
                {
                    "sender": who or token,
                    "body": body,
                    "owner": bool(is_from_me),
                    "when": _apple_timestamp_to_datetime(raw_date),
                }
            )
        return out

    def read_whatsapp_desk_tails(self, *, limit: int = 400) -> list[dict[str, Any]]:
        """Recent live WhatsApp lines grouped later by partner. Ask-only."""

        path = self.whatsapp_db_path
        if not _sqlite_readable(path):
            return []
        cap = max(40, min(int(limit or 400), 800))
        try:
            rows = _sqlite_query(
                path,
                """
                SELECT m.ZMESSAGEDATE, m.ZTEXT, m.ZISFROMME,
                       m.ZPUSHNAME, s.ZPARTNERNAME, m.ZFROMJID, m.ZTOJID,
                       s.ZSESSIONTYPE, s.ZCONTACTJID
                FROM ZWAMESSAGE m
                LEFT JOIN ZWACHATSESSION s ON m.ZCHATSESSION = s.Z_PK
                WHERE m.ZTEXT IS NOT NULL AND trim(m.ZTEXT) != ''
                  AND IFNULL(s.ZSESSIONTYPE, 0) NOT IN (3, 5)
                  AND IFNULL(s.ZCONTACTJID, '') NOT LIKE '%@status%'
                  AND IFNULL(s.ZCONTACTJID, '') NOT LIKE '%@newsletter%'
                ORDER BY m.ZMESSAGEDATE DESC
                LIMIT ?
                """,
                (cap,),
            )
        except sqlite3.OperationalError as exc:
            if "no such column" not in str(exc).lower():
                logger.warning("WhatsApp desk tails skipped", exc_info=False)
                return []
            try:
                rows = _sqlite_query(
                    path,
                    """
                    SELECT m.ZMESSAGEDATE, m.ZTEXT, m.ZISFROMME,
                           m.ZPUSHNAME, s.ZPARTNERNAME, m.ZFROMJID, m.ZTOJID
                    FROM ZWAMESSAGE m
                    LEFT JOIN ZWACHATSESSION s ON m.ZCHATSESSION = s.Z_PK
                    WHERE m.ZTEXT IS NOT NULL AND trim(m.ZTEXT) != ''
                    ORDER BY m.ZMESSAGEDATE DESC
                    LIMIT ?
                    """,
                    (cap,),
                )
                rows = [(*r, 0, "") for r in rows]
            except Exception:
                logger.warning("WhatsApp desk tails skipped", exc_info=False)
                return []
        except Exception:
            logger.warning("WhatsApp desk tails skipped", exc_info=False)
            return []
        out: list[dict[str, Any]] = []
        for raw_date, raw_text, is_from_me, push_name, partner_name, from_jid, to_jid, _sess, _cjid in rows:
            body = str(raw_text or "").strip()
            partner = str(partner_name or push_name or from_jid or to_jid or "").strip()
            if not body or not partner:
                continue
            if _is_whatsapp_system_body(body):
                continue
            if _is_whatsapp_broadcast_channel(_sess, from_jid, to_jid, _cjid):
                continue
            out.append(
                {
                    "sender": partner,
                    "partner": partner,
                    "body": body,
                    "owner": bool(is_from_me),
                    "when": _apple_timestamp_to_datetime(raw_date),
                }
            )
        return out

    def peek_imessage(self, *, tokens: list[str] | None = None, limit: int = 8) -> list[dict[str, Any]]:
        """Read live iMessage/SMS from chat.db. No Event writes."""
        if not self.is_chat_db_accessible():
            return []
        try:
            rows = _sqlite_query(
                self.chat_db_path,
                """
                SELECT message.ROWID, message.date, message.text, handle.id, message.is_from_me
                FROM message
                LEFT JOIN handle ON message.handle_id = handle.ROWID
                WHERE message.text IS NOT NULL AND trim(message.text) != ''
                ORDER BY message.ROWID DESC
                LIMIT 200
                """,
            )
        except Exception:
            logger.warning("iMessage live peek skipped", exc_info=False)
            return []
        hits: list[dict[str, Any]] = []
        for rowid, raw_date, raw_text, handle, is_from_me in rows:
            body = str(raw_text or "").strip()
            if not body:
                continue
            who = "You" if is_from_me else str(handle or "someone").strip()
            occurred = _apple_timestamp_to_datetime(raw_date)
            hits.append(
                {
                    "id": f"imessage-live-{int(rowid or 0)}",
                    "source": "imessage",
                    "when": occurred.isoformat(),
                    "text": f"{who}: {body}"[:400],
                    "handle": str(handle or "").strip(),
                    "preview": body[:220],
                    "kind": "live_mac",
                    "memory_type": "message.imessage.sent" if is_from_me else "message.imessage.received",
                    "confidence": "live_mac",
                    "score": 0.15,
                    "provenance": [f"imessage-live-{int(rowid or 0)}"],
                    "shelf": "chats",
                    "channel": "imessage",
                }
            )
        distinctive = [token for token in (tokens or []) if token]
        if not distinctive:
            # Digest: real people only. OTP/bank SMS stay findable via
            # token searches ("what was my OTP") but must not occupy
            # "recent messages" slots beside WhatsApp chats.
            person = [
                h for h in hits
                if not _is_transactional_sms(str(h.get("preview") or ""), str(h.get("handle") or ""))
            ]
            txn = [
                h for h in hits
                if _is_transactional_sms(str(h.get("preview") or ""), str(h.get("handle") or ""))
            ]
            grouped_people = _group_per_person(person)
            hits = grouped_people or _group_per_person(txn)
        return _filter_peek(hits, distinctive, limit)

    def peek_calls(self, *, tokens: list[str] | None = None, limit: int = 8) -> list[dict[str, Any]]:
        """Read live Continuity call history. No Event writes."""
        path = self.call_db_path
        if not _sqlite_readable(path):
            return []
        try:
            rows = _sqlite_query(
                path,
                """
                SELECT Z_PK, ZDATE, ZDURATION, ZADDRESS, ZNAME, ZORIGINATED, ZANSWERED
                FROM ZCALLRECORD
                ORDER BY Z_PK DESC
                LIMIT 48
                """,
            )
        except Exception:
            logger.warning("Call history live peek skipped", exc_info=False)
            return []
        hits: list[dict[str, Any]] = []
        for pk, raw_date, duration, address, name, originated, answered in rows:
            who = str(name or address or "unknown").strip()
            direction = "outgoing" if originated else "incoming"
            status = "answered" if answered else "missed"
            seconds = int(duration or 0) if isinstance(duration, (int, float)) else 0
            text = f"{status} {direction} call {who}"
            if seconds > 0:
                text = f"{text} ({seconds}s)"
            occurred = _apple_timestamp_to_datetime(raw_date)
            hits.append(
                {
                    "id": f"call-live-{int(pk or 0)}",
                    "source": "calls",
                    "when": occurred.isoformat(),
                    "text": text[:400],
                    "kind": "live_mac",
                    "memory_type": "call.history.recorded",
                    "confidence": "live_mac",
                    "score": 0.15,
                    "provenance": [f"call-live-{int(pk or 0)}"],
                    "shelf": "calls",
                }
            )
        return _filter_peek(hits, [token for token in (tokens or []) if token], limit)

    def peek_photos(self, *, tokens: list[str] | None = None, limit: int = 8) -> list[dict[str, Any]]:
        """Read live Photos filenames. No pixels, no Event writes."""
        path = self.photos_db_path
        if not _sqlite_readable(path):
            return []
        try:
            rows = _sqlite_query(
                path,
                """
                SELECT Z_PK, ZFILENAME, ZDATECREATED
                FROM ZASSET
                WHERE ZFILENAME IS NOT NULL AND trim(ZFILENAME) != ''
                  AND IFNULL(ZTRASHEDSTATE, 0) = 0
                ORDER BY Z_PK DESC
                LIMIT 48
                """,
            )
        except Exception:
            logger.warning("Photos live peek skipped", exc_info=False)
            return []
        hits: list[dict[str, Any]] = []
        for pk, filename, raw_date in rows:
            name = str(filename or "").strip()
            if not name:
                continue
            occurred = _apple_timestamp_to_datetime(raw_date)
            hits.append(
                {
                    "id": f"photo-live-{int(pk or 0)}",
                    "source": "photos",
                    "when": occurred.isoformat(),
                    "text": name[:400],
                    "kind": "live_mac",
                    "memory_type": "photo.library.indexed",
                    "confidence": "live_mac",
                    "score": 0.15,
                    "provenance": [f"photo-live-{int(pk or 0)}"],
                    "shelf": "photos",
                }
            )
        return _filter_peek(hits, [token for token in (tokens or []) if token], limit)

    def peek_contacts(
        self,
        contacts: list[dict[str, Any]] | None = None,
        *,
        tokens: list[str] | None = None,
        limit: int = 8,
    ) -> list[dict[str, Any]]:
        """Format live Apple Contacts rows. No Event writes."""
        hits: list[dict[str, Any]] = []
        for index, contact in enumerate(contacts or []):
            if not isinstance(contact, dict):
                continue
            name = str(
                contact.get("full_name") or contact.get("name") or ""
            ).strip()
            numbers = contact.get("phone_numbers") or []
            emails = contact.get("email_addresses") or []
            phone = str(contact.get("phone") or (numbers[0] if numbers else "") or "").strip()
            email = str(contact.get("email") or (emails[0] if emails else "") or "").strip()
            if not name and not phone and not email:
                continue
            text = name or phone or email
            if name and phone:
                text = f"{name} {phone}"
            elif name and email:
                text = f"{name} {email}"
            cid = str(contact.get("id") or name or index)
            hits.append(
                {
                    "id": f"contact-live-{cid}",
                    "source": "contacts",
                    "when": None,
                    "text": text[:400],
                    "kind": "live_mac",
                    "memory_type": "contact.discovered",
                    "confidence": "live_mac",
                    "score": 0.15,
                    "provenance": [f"contact-live-{cid}"],
                    "shelf": "contacts",
                    "channel": "contacts",
                }
            )
        return _filter_peek(hits, [token for token in (tokens or []) if token], limit)

        return _filter_peek(hits, [token for token in (tokens or []) if token], limit)

    def _mail_index_rows(self, path: str, *, inbox_only: bool) -> list[dict[str, Any]]:
        """Read Envelope Index without launching Mail.app."""
        where = "m.deleted = 0"
        if inbox_only:
            where += " AND (mb.url LIKE '%/INBOX' OR mb.url LIKE '%/INBOX/')"
        rich_sql = f"""
                SELECT replace(replace(COALESCE(sub.subject, ''), char(9), ' '), char(10), ' '),
                       CASE WHEN a.comment != '' THEN a.comment || ' <' || a.address || '>'
                            ELSE COALESCE(a.address, '') END,
                       m.date_received,
                       m.ROWID,
                       COALESCE(snip.summary, ''),
                       g.summary
                FROM messages m
                LEFT JOIN subjects sub ON m.subject = sub.ROWID
                LEFT JOIN addresses a ON m.sender = a.ROWID
                LEFT JOIN mailboxes mb ON m.mailbox = mb.ROWID
                LEFT JOIN summaries snip ON m.summary = snip.ROWID
                LEFT JOIN generated_summaries g ON m.summary = g.ROWID
                WHERE {where}
                ORDER BY m.date_received DESC
                LIMIT 200
                """
        simple_sql = f"""
                SELECT replace(replace(COALESCE(s.subject, ''), char(9), ' '), char(10), ' '),
                       CASE WHEN a.comment != '' THEN a.comment || ' <' || a.address || '>'
                            ELSE COALESCE(a.address, '') END,
                       m.date_received,
                       m.ROWID,
                       '',
                       NULL
                FROM messages m
                LEFT JOIN subjects s ON m.subject = s.ROWID
                LEFT JOIN addresses a ON m.sender = a.ROWID
                LEFT JOIN mailboxes mb ON m.mailbox = mb.ROWID
                WHERE {where}
                ORDER BY m.date_received DESC
                LIMIT 200
                """
        fetched: list[tuple] = []
        try:
            fetched = _sqlite_query(path, rich_sql)
        except Exception:
            try:
                fetched = _sqlite_query(path, simple_sql)
            except Exception:
                logger.warning("Mail live peek skipped", exc_info=False)
                return []
        rows: list[dict[str, Any]] = []
        for subject, sender, raw_date, rowid, snippet, generated in fetched:
            rows.append(
                {
                    "subject": str(subject or "").strip(),
                    "sender": str(sender or "").strip(),
                    "received": _mail_received_iso(raw_date),
                    "rowid": int(rowid) if rowid is not None else None,
                    "snippet": str(snippet or "").strip(),
                    "generated_summary": generated,
                }
            )
        return rows

    def peek_mail(
        self,
        items: list[dict[str, Any]] | None = None,
        *,
        tokens: list[str] | None = None,
        limit: int = 8,
        query: str = "",
    ) -> list[dict[str, Any]]:
        """Read live Mail envelopes and ask-time gists. No body Event writes."""
        from app.memory.mail_speak import (
            generated_summary_text,
            gist_from_preview,
            mail_selector,
        )

        rows = items
        if rows is None:
            path = self.refresh_mail_index_path()
            if not _sqlite_readable(path):
                return []
            fetched = self._mail_index_rows(path, inbox_only=True)
            if not fetched:
                fetched = self._mail_index_rows(path, inbox_only=False)
            rows = fetched
        selector = mail_selector(query)
        wanted = [token for token in (tokens or []) if token] or selector.tokens()
        hits: list[dict[str, Any]] = []
        for index, item in enumerate(rows or []):
            if not isinstance(item, dict):
                continue
            subject = str(item.get("subject") or "").strip()
            sender = str(item.get("sender") or "").strip()
            if not subject and not sender:
                continue
            generated = generated_summary_text(
                item.get("generated_summary") or item.get("generated")
            )
            snippet = str(item.get("snippet") or item.get("preview") or "").strip()
            preview = generated or snippet
            gist = gist_from_preview(preview, subject=subject, want=wanted)
            if not gist:
                gist = subject
            text = f"{subject} from {sender}".strip() if subject and sender else (subject or sender)
            if gist and gist.lower() not in text.lower():
                text = f"{text}. {gist}".strip(" .")
            received = _mail_received_iso(item.get("received"))
            rowid = item.get("rowid")
            try:
                rowid_n = int(rowid) if rowid is not None else None
            except (TypeError, ValueError):
                rowid_n = None
            hits.append(
                {
                    "id": f"mail-live-{index}-{text[:40]}",
                    "source": "mail",
                    "when": received,
                    "text": text[:400],
                    "subject": subject,
                    "sender": sender,
                    "gist": gist,
                    "snippet": snippet[:2400],
                    "rowid": rowid_n,
                    "kind": "live_mac",
                    "memory_type": "mail.envelope.received",
                    "confidence": "live_mac",
                    "score": 0.15,
                    "provenance": [f"mail-live-{index}"],
                    "shelf": "mail",
                    "channel": "mail",
                    "gist_source": "generated" if generated else ("snippet" if snippet else "subject"),
                }
            )
        distinctive = [token for token in wanted if token]
        if not distinctive:
            personal = [
                hit
                for hit in hits
                if not _is_bulk_mail(str(hit.get("sender") or ""), str(hit.get("subject") or ""))
            ]
            bulk = [
                hit
                for hit in hits
                if _is_bulk_mail(str(hit.get("sender") or ""), str(hit.get("subject") or ""))
            ]
            contacts = list(getattr(self, "_cached_contacts", []) or [])
            if contacts and personal:
                known = [
                    hit
                    for hit in personal
                    if _mail_sender_in_contacts(str(hit.get("sender") or ""), contacts)
                ]
                other = [hit for hit in personal if hit not in known]
                personal = known + other
            # Unscoped recents: people (address-book first) before one-way bulk.
            hits = personal if personal else bulk
        filtered = _filter_peek(hits, wanted, limit)
        if selector.particular and filtered:
            self._enrich_mail_gist(filtered[0], wanted=wanted)
        return filtered

    def _enrich_mail_gist(self, hit: dict[str, Any], *, wanted: list[str]) -> None:
        """Ask-time .emlx gist for a particular mail when the index has no snippet."""
        from app.memory.mail_speak import find_emlx, gist_from_preview, preview_from_emlx

        if str(hit.get("gist_source") or "") != "subject":
            return
        rowid = hit.get("rowid")
        if not rowid or not self.mail_index_path:
            return
        version_root = str(Path(self.mail_index_path).resolve().parent.parent)
        path = find_emlx(version_root, int(rowid))
        if path is None:
            return
        preview = preview_from_emlx(path)
        if not preview:
            return
        subject = str(hit.get("subject") or "")
        gist = gist_from_preview(preview, subject=subject, want=wanted)
        if not gist:
            return
        hit["gist"] = gist
        hit["gist_source"] = "emlx"
        text = str(hit.get("text") or "")
        if gist.lower() not in text.lower():
            hit["text"] = f"{text}. {gist}".strip(" .")[:400]

    async def sync_contacts_delta(
        self,
        session: AsyncSession,
        contacts: list[dict],
    ) -> list[Any]:
        """Ingest new or modified contacts as immutable events."""
        events = []
        event_service = EventService(session, actor="life_stream_daemon")

        for contact in contacts:
            cid = str(contact.get("id") or contact.get("name") or "")
            if not cid:
                continue

            is_new = cid not in self._known_contact_ids
            self._known_contact_ids.add(cid)

            fingerprint = _contact_fingerprint(contact)
            if not is_new and self._contact_fps.get(cid) == fingerprint:
                continue
            self._contact_fps[cid] = fingerprint
            if len(self._contact_fps) > _MAX_CONTACT_FPS:
                extra = list(self._contact_fps)[: len(self._contact_fps) - _MAX_CONTACT_FPS]
                for key in extra:
                    self._contact_fps.pop(key, None)
                    self._known_contact_ids.discard(key)

            event_type = "contact.discovered" if is_new else "contact.updated"
            phone = contact.get("phone") or ""
            if not phone and contact.get("phone_numbers"):
                numbers = contact.get("phone_numbers") or []
                phone = numbers[0] if numbers else ""
            email = contact.get("email") or ""
            if not email and contact.get("email_addresses"):
                addresses = contact.get("email_addresses") or []
                email = addresses[0] if addresses else ""
            event_create = EventCreate(
                event_type=event_type,
                source="contacts",
                content={
                    "contact_id": cid,
                    "name": contact.get("name") or contact.get("full_name") or "",
                    "phone": phone,
                    "email": email,
                    "company": contact.get("company") or "",
                },
                privacy_level="sensitive",
                metadata={"source": "apple_contacts"},
            )
            created_event = await event_service.create(event_create)
            events.append(created_event)

        if events:
            await session.commit()

        return events

    async def sync_mail_delta(
        self,
        session: AsyncSession,
        items: list[dict],
    ) -> list[Any]:
        """Ingest new Mail envelopes as immutable events. Subjects only, no bodies."""
        events = []
        event_service = EventService(session, actor="life_stream_daemon")
        for item in items:
            subject = str(item.get("subject") or "").strip()
            sender = str(item.get("sender") or "").strip()
            received = str(item.get("received") or "").strip()
            if not subject and not sender:
                continue
            fingerprint = f"{subject}|{sender}|{received}"
            if self._mail_fps.get(fingerprint) == "1":
                continue
            if len(self._mail_fps) >= _MAX_CONTACT_FPS:
                extra = list(self._mail_fps)[: len(self._mail_fps) - _MAX_CONTACT_FPS + 1]
                for key in extra:
                    self._mail_fps.pop(key, None)
            self._mail_fps[fingerprint] = "1"
            text = f"{subject} from {sender}".strip()
            event_create = EventCreate(
                event_type="mail.envelope.received",
                source="mail",
                content={
                    "text": text,
                    "subject": subject,
                    "sender": sender,
                    "received": received,
                },
                privacy_level="sensitive",
                metadata={"source": "apple_mail", "channel": "mail"},
            )
            created_event = await event_service.create(event_create)
            events.append(created_event)

        if events:
            await session.commit()
        return events

    async def sync_calendar_delta(
        self,
        session: AsyncSession,
        items: list[dict],
    ) -> list[Any]:
        """Ingest calendar envelopes. Titles and times only."""
        events = []
        event_service = EventService(session, actor="life_stream_daemon")
        for item in items:
            summary = str(item.get("summary") or item.get("title") or "").strip()
            start = str(item.get("start") or "").strip()
            event_id = str(item.get("event_id") or item.get("id") or "").strip()
            if not summary and not event_id:
                continue
            fingerprint = event_id or f"{summary}|{start}"
            if self._calendar_fps.get(fingerprint) == "1":
                continue
            if len(self._calendar_fps) >= _MAX_CONTACT_FPS:
                extra = list(self._calendar_fps)[: len(self._calendar_fps) - _MAX_CONTACT_FPS + 1]
                for key in extra:
                    self._calendar_fps.pop(key, None)
            self._calendar_fps[fingerprint] = "1"
            location = str(item.get("location") or "").strip()
            end = str(item.get("end") or "").strip()
            text = summary if not start else f"{summary} at {start}"
            event_create = EventCreate(
                event_type="calendar.event.recorded",
                source="calendar",
                content={
                    "text": text,
                    "summary": summary,
                    "start": start,
                    "end": end,
                    "location": location,
                    "event_id": event_id,
                },
                privacy_level="sensitive",
                metadata={"source": "google_calendar", "channel": "calendar"},
            )
            created_event = await event_service.create(event_create)
            events.append(created_event)

        if events:
            await session.commit()
        return events

    async def sync_health_delta(
        self,
        session: AsyncSession,
        items: list[dict] | None = None,
    ) -> list[Any]:
        """Record compact health snapshots as events. Metrics only, no dump into chat."""
        from app.models import HealthSnapshot

        rows: list[Any]
        if items:
            rows = items
        else:
            result = await session.execute(
                select(HealthSnapshot).order_by(HealthSnapshot.occurred_at.desc()).limit(8)
            )
            rows = list(result.scalars().all())
        events = []
        event_service = EventService(session, actor="life_stream_daemon")
        for row in rows:
            payload = health_snapshot_event_create(row)
            if payload is None:
                continue
            sid = str((payload.metadata or {}).get("snapshot_id") or "")
            if not sid or self._health_fps.get(sid) == "1":
                continue
            if len(self._health_fps) >= _MAX_CONTACT_FPS:
                extra = list(self._health_fps)[: len(self._health_fps) - _MAX_CONTACT_FPS + 1]
                for key in extra:
                    self._health_fps.pop(key, None)
            self._health_fps[sid] = "1"
            created_event = await event_service.create(payload)
            events.append(created_event)

        if events:
            await session.commit()
        return events

    def account_pull_due(self) -> bool:
        return (time.time() - self._last_account_pull) >= _ACCOUNT_PULL_SECONDS

    def mark_account_pulled(self) -> None:
        self._last_account_pull = time.time()

    async def tick(
        self,
        session: AsyncSession,
        *,
        sample_contacts: list[dict] | None = None,
        sample_mail: list[dict] | None = None,
        sample_calendar: list[dict] | None = None,
        sample_health: list[dict] | None = None,
    ) -> dict[str, Any]:
        """Run a single sensory tick across all observed local life streams."""
        imessage_events = await self._safe_sync(
            "imessage", self.sync_imessage(session, limit=25), session
        )
        whatsapp_events = await self._safe_sync(
            "whatsapp", self.sync_whatsapp(session, limit=25), session
        )
        call_events = await self._safe_sync(
            "calls", self.sync_calls(session, limit=25), session
        )
        photo_events = await self._safe_sync(
            "photos", self.sync_photos(session, limit=25), session
        )
        # Every stream is isolated: one bad sample must not kill the tick
        # or skip save_cursor() (an unsaved tick re-ingests on restart).
        if sample_contacts:
            contact_events = await self._safe_sync(
                "contacts", self.sync_contacts_delta(session, sample_contacts), session
            )
        else:
            contact_events = []
        if sample_mail:
            mail_events = await self._safe_sync(
                "mail", self.sync_mail_delta(session, sample_mail), session
            )
        else:
            mail_events = []
        if sample_calendar:
            calendar_events = await self._safe_sync(
                "calendar", self.sync_calendar_delta(session, sample_calendar), session
            )
        else:
            calendar_events = []
        if sample_health:
            health_events = await self._safe_sync(
                "health", self.sync_health_delta(session, sample_health), session
            )
        else:
            health_events = []

        self.save_cursor()
        return {
            "ok": True,
            "messages_ingested": len(imessage_events),
            "whatsapp_ingested": len(whatsapp_events),
            "calls_ingested": len(call_events),
            "photos_ingested": len(photo_events),
            "contacts_ingested": len(contact_events),
            "mail_ingested": len(mail_events),
            "calendar_ingested": len(calendar_events),
            "health_ingested": len(health_events),
            "latest_message_rowid": self.last_message_rowid,
            "latest_whatsapp_pk": self.last_whatsapp_pk,
            "latest_call_pk": self.last_call_pk,
            "latest_photo_pk": self.last_photo_pk,
            "chat_db_accessible": self.is_chat_db_accessible(),
        }

    def attach_cursor(self, path: str | os.PathLike[str] | None) -> None:
        if not path:
            return
        self._cursor_path = Path(path).expanduser()
        self.load_cursor()

    def load_cursor(self) -> None:
        path = self._cursor_path
        if path is None or not path.is_file():
            return
        try:
            payload = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            return
        rowid = payload.get("last_message_rowid")
        if isinstance(rowid, int) and rowid >= 0:
            self.last_message_rowid = rowid
        for key, attr in (
            ("last_whatsapp_pk", "last_whatsapp_pk"),
            ("last_call_pk", "last_call_pk"),
            ("last_photo_pk", "last_photo_pk"),
        ):
            value = payload.get(key)
            if isinstance(value, int) and value >= 0:
                setattr(self, attr, value)
                if value > 0:
                    self._bootstrapped.add(attr)
        fps = payload.get("contact_fps")
        if isinstance(fps, dict):
            self._contact_fps = {str(key): str(value) for key, value in fps.items()}
            self._known_contact_ids = set(self._contact_fps)
        mail_fps = payload.get("mail_fps")
        if isinstance(mail_fps, dict):
            self._mail_fps = {str(key): str(value) for key, value in mail_fps.items()}
        calendar_fps = payload.get("calendar_fps")
        if isinstance(calendar_fps, dict):
            self._calendar_fps = {str(key): str(value) for key, value in calendar_fps.items()}
        health_fps = payload.get("health_fps")
        if isinstance(health_fps, dict):
            self._health_fps = {str(key): str(value) for key, value in health_fps.items()}
        pulled = payload.get("last_account_pull")
        if isinstance(pulled, (int, float)) and pulled >= 0:
            self._last_account_pull = float(pulled)

    def save_cursor(self) -> None:
        path = self._cursor_path
        if path is None:
            return
        try:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(
                json.dumps(
                    {
                        "last_message_rowid": self.last_message_rowid,
                        "last_whatsapp_pk": self.last_whatsapp_pk,
                        "last_call_pk": self.last_call_pk,
                        "last_photo_pk": self.last_photo_pk,
                        "contact_fps": self._contact_fps,
                        "mail_fps": self._mail_fps,
                        "calendar_fps": self._calendar_fps,
                        "health_fps": self._health_fps,
                        "last_account_pull": self._last_account_pull,
                    }
                ),
                encoding="utf-8",
            )
        except OSError:
            logger.debug("life_stream cursor save skipped", exc_info=True)


_PROCESS_DAEMON: LifeStreamDaemon | None = None


def get_life_stream_daemon() -> LifeStreamDaemon:
    """Process-local daemon so incremental rowids survive scheduler ticks."""
    global _PROCESS_DAEMON
    if _PROCESS_DAEMON is None:
        from app.config import settings

        _PROCESS_DAEMON = LifeStreamDaemon()
        _PROCESS_DAEMON.attach_cursor(
            getattr(settings, "life_stream_cursor_path", "") or None
        )
    return _PROCESS_DAEMON
