// Generated by package.sh — do not edit.
import Foundation
enum BuildInfo {
    static let gitSHA = "0dc42dd140dc77a422b39faefb386a2cea8b9f03"
    static let buildTimestamp = "20260827T073500Z"
    static let audioArchitecture = "mac-source-ring-v1"
}
