// Generated by package.sh — do not edit.
import Foundation
enum BuildInfo {
    static let gitSHA = "1263d7f83f51c45d7e7c4193b5795aa0b79f27bf"
    static let buildTimestamp = "20261008T072009Z"
    static let audioArchitecture = "mac-player-node-v1"
}
