// Generated by package.sh — do not edit.
import Foundation
enum BuildInfo {
    static let gitSHA = "d6d99a5b61a6e14b95516a41f9d37e2703620b06"
    static let buildTimestamp = "20260829T110203Z"
    static let audioArchitecture = "mac-player-node-v1"
}
