#!/bin/zsh
# Package the SwiftPM-built EV menu-bar app into build/EV.app without Xcode.
#
# TCC (the privacy database) records permissions against a code signature, so
# the signing steps below are not cosmetic: a bundle that fails to sign never
# appears in System Settings > Privacy & Security and can never hold a grant.
# Every codesign invocation therefore fails the build instead of being ignored.
#
# Usage:
#   ./scripts/package.sh              # build + sign into build/EV.app
#   ./scripts/package.sh --install    # ... then install into /Applications
#
# Environment:
#   EV_CODESIGN_IDENTITY  signing identity (default "-", ad-hoc). An ad-hoc
#                         identity is a cdhash, which changes on every rebuild,
#                         so macOS treats each build as a different app and
#                         previously granted permissions stop applying. Pass a
#                         Developer ID or a self-signed identity from your
#                         keychain (see `security find-identity -v -p
#                         codesigning`) for an identity that survives rebuilds.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

# Embed build provenance so the running binary can prove its source
GIT_SHA="$(git -C "$ROOT/.." rev-parse HEAD 2>/dev/null || git rev-parse HEAD 2>/dev/null || echo "unknown")"
BUILD_TS="$(date -u +%Y%m%dT%H%M%SZ)"
AUDIO_ARCH="mac-player-node-v1"
cat > "$ROOT/Sources/EV/BuildInfo.swift" <<EOF
// Generated by package.sh — do not edit.
import Foundation
enum BuildInfo {
    static let gitSHA = "$GIT_SHA"
    static let buildTimestamp = "$BUILD_TS"
    static let audioArchitecture = "$AUDIO_ARCH"
}
EOF
# Stamp Info.plist as well so codesign and Finder show it
plutil -replace EVGitSHA -string "$GIT_SHA" "$ROOT/Resources/Info.plist" 2>/dev/null || plutil -insert EVGitSHA -string "$GIT_SHA" "$ROOT/Resources/Info.plist" 2>/dev/null || true
plutil -replace EVAudioArchitecture -string "$AUDIO_ARCH" "$ROOT/Resources/Info.plist" 2>/dev/null || plutil -insert EVAudioArchitecture -string "$AUDIO_ARCH" "$ROOT/Resources/Info.plist" 2>/dev/null || true
plutil -replace EVBuildTimestamp -string "$BUILD_TS" "$ROOT/Resources/Info.plist" 2>/dev/null || plutil -insert EVBuildTimestamp -string "$BUILD_TS" "$ROOT/Resources/Info.plist" 2>/dev/null || true
INSTALL=0
for arg in "$@"; do
    case "$arg" in
        --install) INSTALL=1 ;;
        *) echo "unknown argument: $arg" >&2; exit 2 ;;
    esac
done

IDENTITY="${EV_CODESIGN_IDENTITY:--}"
ENTITLEMENTS="$ROOT/Resources/EV.entitlements"

swift build -c release

# SwiftPM now puts release products in an arch-specific directory
BIN_DIR="$(swift build -c release --show-bin-path 2>/dev/null || echo "$ROOT/.build/release")"
BIN="$BIN_DIR/EV"
HELPER="$BIN_DIR/EVNotificationHelper"
LIFE_HELPER="$BIN_DIR/EVLifeHelper"
# Fallback for older toolchains
if [[ ! -f "$BIN" ]]; then
    BIN="$ROOT/.build/release/EV"
    HELPER="$ROOT/.build/release/EVNotificationHelper"
    LIFE_HELPER="$ROOT/.build/release/EVLifeHelper"
fi
if [[ ! -f "$BIN" ]]; then
    BIN="$ROOT/.build/arm64-apple-macosx/release/EV"
    HELPER="$ROOT/.build/arm64-apple-macosx/release/EVNotificationHelper"
    LIFE_HELPER="$ROOT/.build/arm64-apple-macosx/release/EVLifeHelper"
fi
if [[ ! -f "$BIN" ]]; then
    echo "ERROR: EV binary not found at $BIN" >&2
    exit 1
fi
if [[ ! -f "$HELPER" ]]; then
    echo "ERROR: EVNotificationHelper not found at $HELPER (build with --product EVNotificationHelper)" >&2
    exit 1
fi
if [[ ! -f "$LIFE_HELPER" ]]; then
    echo "ERROR: EVLifeHelper not found at $LIFE_HELPER" >&2
    exit 1
fi
APP="$ROOT/build/EV.app"

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

cp "$BIN" "$APP/Contents/MacOS/EV"
cp "$HELPER" "$APP/Contents/MacOS/EVNotificationHelper"
cp "$LIFE_HELPER" "$APP/Contents/MacOS/EVLifeHelper"
cp "$ROOT/Resources/Info.plist" "$APP/Contents/Info.plist"
cp -R "$ROOT/Resources/orb" "$APP/Contents/Resources/orb"

if [[ ! -f "$APP/Contents/Resources/orb/filament-orb.mp4" ]]; then
    echo "ERROR: filament-orb.mp4 missing from $APP" >&2
    exit 1
fi
if [[ ! -f "$APP/Contents/Resources/orb/BUILD_ID.txt" ]]; then
    echo "ERROR: BUILD_ID.txt missing from $APP" >&2
    exit 1
fi
if grep -R -l 'three.module.js\|UnrealBloomPass\|index.html' "$APP/Contents/Resources/orb" >/dev/null 2>&1; then
    echo "ERROR: stale Three.js orb assets were copied into $APP" >&2
    exit 1
fi
if ! grep -a -q 'metal-video-quad-v4-presence' "$APP/Contents/MacOS/EV"; then
    echo "ERROR: packaged binary is missing the current orb renderer identity" >&2
    exit 1
fi
if ! grep -a -q 'ev-barge-runtime-v2' "$APP/Contents/MacOS/EV"; then
    echo "ERROR: packaged binary is missing the barge-in runtime marker" >&2
    exit 1
fi
if grep -a -q 'VoiceOrbFallbackView' "$APP/Contents/MacOS/EV"; then
    echo "ERROR: packaged binary still contains the WKWebView orb fallback" >&2
    exit 1
fi
echo "Orb identity: $(tr '\n' ' ' < "$APP/Contents/Resources/orb/BUILD_ID.txt")"

# Sign with the stable self-signed "EV Code Signing" identity created by
# signing.sh. TCC ties every permission grant to the app's code signature;
# ad-hoc (--sign -) signatures change the CDHash on every rebuild, so each
# rebuild looks like a brand-new app and all granted permissions are silently
# forgotten. The fixed identity keeps the signature (and therefore the TCC
# grants) stable across rebuilds.
IDENTITY="$(./scripts/signing.sh 2>/dev/null || true)"
if [ -n "$IDENTITY" ]; then
    codesign --force --deep --sign "$IDENTITY" \
        --entitlements "$ROOT/Resources/EV.entitlements" \
        "$APP" >/dev/null 2>&1
    codesign --verify --deep --strict "$APP" >/dev/null 2>&1 || {
        echo "ERROR: codesign --verify failed for $APP" >&2
        exit 1
    }
    echo "Signed $APP with stable identity: $IDENTITY"
    echo "Signature: $(codesign -dv --verbose=4 "$APP" 2>&1 | grep -E '^(Signature|TeamIdentifier|Identifier)')"
else
    echo "ERROR: no stable code-signing identity available." >&2
    echo "       TCC permission grants are tied to the code signature; an ad-hoc" >&2
    echo "       signature changes its CDHash on every rebuild, so macOS forgets" >&2
    echo "       every granted permission (Microphone, Camera, …) after each build." >&2
    echo "       Run ./scripts/signing.sh to create the 'EV Code Signing' identity," >&2
    echo "       then re-run ./scripts/package.sh." >&2
    exit 1
fi
# A copied or downloaded bundle carries com.apple.quarantine, which makes macOS
# run the app from a random read-only App Translocation mount. Its TCC identity
# then changes on every launch and no grant ever sticks. `xattr -d` also exits
# non-zero when the attribute is already absent, which is the state we want.
xattr -dr com.apple.quarantine "$APP" 2>/dev/null || true

if [ "$IDENTITY" = "-" ]; then
    echo "codesign identity: - (ad-hoc)"
    echo "  warning: ad-hoc identities change on every rebuild. macOS will ask"
    echo "  for permissions again after each package run, and stale EV entries"
    echo "  can pile up in System Settings. Set EV_CODESIGN_IDENTITY to a real"
    echo "  identity for grants that survive rebuilds."
    # The hardened runtime is signable ad-hoc but buys nothing locally, and a
    # secure timestamp needs a real certificate.
    SIGN_OPTIONS=(--timestamp=none)
else
    echo "codesign identity: $IDENTITY"
    # The hardened runtime is only meaningful with a real identity; it also
    # requires the entitlements below or the mic/camera calls are refused.
    SIGN_OPTIONS=(--options runtime --timestamp)
fi

# The helper is a second Mach-O inside Contents/MacOS and must be signed before
# the outer bundle, otherwise the app signature seals an unsigned nested binary
# and verification fails. This is what --deep used to paper over; --deep is
# deprecated for signing and must not be used.
codesign --force --sign "$IDENTITY" \
    --identifier "com.ev.suit.notification-helper" \
    "${SIGN_OPTIONS[@]}" \
    "$APP/Contents/MacOS/EVNotificationHelper"

codesign --force --sign "$IDENTITY" \
    --identifier "com.ev.suit" \
    "${SIGN_OPTIONS[@]}" \
    --entitlements "$ENTITLEMENTS" \
    "$APP"

echo
echo "signature:"
codesign -dv --verbose=2 "$APP" 2>&1 | sed 's/^/  /'

echo
echo "verify:"
codesign --verify --strict --verbose=2 "$APP" 2>&1 | sed 's/^/  /'

echo
echo "spctl (report only; ad-hoc and self-signed builds are expected to be rejected):"
spctl --assess --type execute --verbose=4 "$APP" 2>&1 | sed 's/^/  /' || true

echo
echo "Packaged $APP"

# CANONICAL MASTER AUTHORITY: production secret lives at ~/.ev/secrets/production.env
# (loaded via app.config secret overlay). api.env is SAFE LOCAL CONFIG ONLY
# and MUST NOT contain EV_MASTER_KEY or device secrets. Device tokens live
# in Keychain (com.ev.suit), not in files that package.sh could overwrite.
# Normal EV.app startup uses Keychain device token, not master.
sync_api_env() {
    local dest="${HOME}/Library/Application Support/EV/api.env"
    mkdir -p "$(dirname "$dest")"
    local url="http://127.0.0.1:8000"
    local src="$ROOT/../.env"
    if [[ -f "$src" ]]; then
        local src_url
        src_url="$(awk -F= '/^EV_API_URL=/{v=$2} END{print v}' "$src" | tr -d "\"'")"
        if [[ -n "$src_url" ]]; then
            url="$src_url"
        fi
    fi
    url="${EV_API_URL:-$url}"
    umask 077
    printf 'EV_API_URL=%s\n' "$url" > "$dest"
    # Keep legacy cleanup: remove any master/device secrets that may have
    # drifted into api.env or UserDefaults. Device token stays in Keychain.
    if grep -q "EV_MASTER_KEY" "$dest" 2>/dev/null || grep -q "EV_API_KEY" "$dest" 2>/dev/null; then
        # File was just overwritten without keys, so nothing to do; but if an old
        # file existed with keys, it is now replaced. Log for visibility.
        true
    fi
    # Do NOT write EV_MASTER_KEY or EV_API_KEY to api.env or defaults.
    # Clean any legacy UserDefaults master that would be mistaken for device cred.
    defaults delete com.ev.suit EV_API_KEY 2>/dev/null || true
    defaults write com.ev.suit EV_API_URL "$url" 2>/dev/null || true
    echo "Wrote safe API URL for EV.app → $dest (master/device secrets NOT written; device token in Keychain com.ev.suit)"
}
sync_api_env
if [ "$INSTALL" -eq 1 ]; then
    echo
    exec "$ROOT/scripts/install.sh"
fi

echo "Run ./scripts/install.sh to install into /Applications — TCC grants are"
echo "unstable while the app runs from build/."
