#!/bin/zsh
# Package the SwiftPM-built EV menu-bar app into build/EV.app without Xcode.
#
# Usage: ./scripts/package.sh

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

# Embed build provenance so the running binary can prove its source
GIT_SHA="$(git -C "$ROOT/.." rev-parse HEAD 2>/dev/null || git rev-parse HEAD 2>/dev/null || echo "unknown")"
BUILD_TS="$(date -u +%Y%m%dT%H%M%SZ)"
AUDIO_ARCH="mac-source-ring-v1"
cat > "$ROOT/Sources/EV/BuildInfo.swift" <<EOF
// Generated by package.sh — do not edit.
import Foundation
enum BuildInfo {
    static let gitSHA = "$GIT_SHA"
    static let buildTimestamp = "$BUILD_TS"
    static let audioArchitecture = "$AUDIO_ARCH"
}
EOF
# Stamp Info.plist as well so codesign and Finder show it
plutil -replace EVGitSHA -string "$GIT_SHA" "$ROOT/Resources/Info.plist" 2>/dev/null || plutil -insert EVGitSHA -string "$GIT_SHA" "$ROOT/Resources/Info.plist" 2>/dev/null || true
plutil -replace EVAudioArchitecture -string "$AUDIO_ARCH" "$ROOT/Resources/Info.plist" 2>/dev/null || plutil -insert EVAudioArchitecture -string "$AUDIO_ARCH" "$ROOT/Resources/Info.plist" 2>/dev/null || true
plutil -replace EVBuildTimestamp -string "$BUILD_TS" "$ROOT/Resources/Info.plist" 2>/dev/null || plutil -insert EVBuildTimestamp -string "$BUILD_TS" "$ROOT/Resources/Info.plist" 2>/dev/null || true

swift build -c release --product EV

# SwiftPM now puts release products in an arch-specific directory
BIN_DIR="$(swift build -c release --show-bin-path 2>/dev/null || echo "$ROOT/.build/release")"
BIN="$BIN_DIR/EV"
HELPER="$BIN_DIR/EVNotificationHelper"
LIFE_HELPER="$BIN_DIR/EVLifeHelper"
# Fallback for older toolchains
if [[ ! -f "$BIN" ]]; then
    BIN="$ROOT/.build/release/EV"
    HELPER="$ROOT/.build/release/EVNotificationHelper"
    LIFE_HELPER="$ROOT/.build/release/EVLifeHelper"
fi
if [[ ! -f "$BIN" ]]; then
    BIN="$ROOT/.build/arm64-apple-macosx/release/EV"
    HELPER="$ROOT/.build/arm64-apple-macosx/release/EVNotificationHelper"
    LIFE_HELPER="$ROOT/.build/arm64-apple-macosx/release/EVLifeHelper"
fi
APP="$ROOT/build/EV.app"

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

cp "$BIN" "$APP/Contents/MacOS/EV"
cp "$HELPER" "$APP/Contents/MacOS/EVNotificationHelper"
cp "$LIFE_HELPER" "$APP/Contents/MacOS/EVLifeHelper"
cp "$ROOT/Resources/Info.plist" "$APP/Contents/Info.plist"
cp -R "$ROOT/Resources/orb" "$APP/Contents/Resources/orb"

if [[ ! -f "$APP/Contents/Resources/orb/filament-orb.mp4" ]]; then
    echo "ERROR: filament-orb.mp4 missing from $APP" >&2
    exit 1
fi
if [[ ! -f "$APP/Contents/Resources/orb/BUILD_ID.txt" ]]; then
    echo "ERROR: BUILD_ID.txt missing from $APP" >&2
    exit 1
fi
if grep -R -l 'three.module.js\|UnrealBloomPass\|index.html' "$APP/Contents/Resources/orb" >/dev/null 2>&1; then
    echo "ERROR: stale Three.js orb assets were copied into $APP" >&2
    exit 1
fi
if ! grep -a -q 'metal-video-quad-v4-presence' "$APP/Contents/MacOS/EV"; then
    echo "ERROR: packaged binary is missing the current orb renderer identity" >&2
    exit 1
fi
if ! grep -a -q 'ev-barge-runtime-v2' "$APP/Contents/MacOS/EV"; then
    echo "ERROR: packaged binary is missing the barge-in runtime marker" >&2
    exit 1
fi
if grep -a -q 'VoiceOrbFallbackView' "$APP/Contents/MacOS/EV"; then
    echo "ERROR: packaged binary still contains the WKWebView orb fallback" >&2
    exit 1
fi
echo "Orb identity: $(tr '\n' ' ' < "$APP/Contents/Resources/orb/BUILD_ID.txt")"

# Sign with the stable self-signed "EV Code Signing" identity created by
# signing.sh. TCC ties every permission grant to the app's code signature;
# ad-hoc (--sign -) signatures change the CDHash on every rebuild, so each
# rebuild looks like a brand-new app and all granted permissions are silently
# forgotten. The fixed identity keeps the signature (and therefore the TCC
# grants) stable across rebuilds.
IDENTITY="$(./scripts/signing.sh 2>/dev/null || true)"
if [ -n "$IDENTITY" ]; then
    codesign --force --deep --sign "$IDENTITY" \
        --entitlements "$ROOT/Resources/EV.entitlements" \
        "$APP" >/dev/null 2>&1
    codesign --verify --deep --strict "$APP" >/dev/null 2>&1 || {
        echo "ERROR: codesign --verify failed for $APP" >&2
        exit 1
    }
    echo "Signed $APP with stable identity: $IDENTITY"
    echo "Signature: $(codesign -dv --verbose=4 "$APP" 2>&1 | grep -E '^(Signature|TeamIdentifier|Identifier)')"
else
    echo "ERROR: no stable code-signing identity available." >&2
    echo "       TCC permission grants are tied to the code signature; an ad-hoc" >&2
    echo "       signature changes its CDHash on every rebuild, so macOS forgets" >&2
    echo "       every granted permission (Microphone, Camera, …) after each build." >&2
    echo "       Run ./scripts/signing.sh to create the 'EV Code Signing' identity," >&2
    echo "       then re-run ./scripts/package.sh." >&2
    exit 1
fi

echo "Packaged $APP"

# DO NOT CHANGE — sync_api_env writes EV_MASTER_KEY (>=16 chars) only.
# Never copy EV_EARS_API_KEY / "dev" / "changeme" here; that 401s EV.app.
# The GUI app is not launched from the repo shell, so copy the local API
# credentials where AppConfig can find them. Never echo the key.
sync_api_env() {
    local src="$ROOT/../.env"
    local dest="${HOME}/Library/Application Support/EV/api.env"
    mkdir -p "$(dirname "$dest")"
    local url="http://127.0.0.1:8000"
    local key=""
    if [[ -f "$src" ]]; then
        url="$(awk -F= '/^EV_API_URL=/{v=$2} END{print v}' "$src" | tr -d "\"'")"
        key="$(awk -F= '/^EV_MASTER_KEY=/{v=$2} END{print v}' "$src" | tr -d "\"'")"
        if [[ -z "$key" || ${#key} -lt 16 ]]; then
            key="$(awk -F= '/^EV_API_KEY=/{v=$2} END{print v}' "$src" | tr -d "\"'")"
        fi
    fi
    url="${EV_API_URL:-${url:-http://127.0.0.1:8000}}"
    key="${EV_MASTER_KEY:-${EV_API_KEY:-$key}}"
    if [[ -n "$key" && "$key" != "dev" && ${#key} -ge 16 ]]; then
        umask 077
        printf 'EV_API_URL=%s\nEV_API_KEY=%s\nEV_MASTER_KEY=%s\n' "$url" "$key" "$key" > "$dest"
        defaults write com.ev.suit EV_API_URL "$url"
        defaults write com.ev.suit EV_API_KEY "$key"
        echo "Wrote API credentials for EV.app → $dest"
    else
        echo "WARNING: no EV_API_KEY/EV_MASTER_KEY found; EV.app will 401 on chat/voice." >&2
    fi
}
sync_api_env
